### ISSUE TITLE
What else would be good for v0.12.0?

### ISSUE THREAD

**Issue by grimfang4** [grimfang4/sdl-gpu#10]
There are already a lot of good changes and new features in 0.11.0 that will be released as 0.12.0, but here are some more possibilities:

Direct VBO support
GLES 3 renderer
GL 4 renderer

**Comment by masonwheeler** [comment]
Multitexture blit support: allow a blit that takes more than one texture and source rect as inputs, and then combines the data in a shader.

Specific use case where this is necessary: textured text.  You get the shape of the text from FTGL or SDL_TTF, but you want to draw it in something more complicated than a simple color.  For this you need multitexturing, passing the text shape and the text texture as the two inputs and combining the alpha of the first texture and the RGB of the second.

Implementation is actually a lot less complicated than it sounds, particularly if you put the burden of writing the shader on the developer rather than building it in to SDL_GPU.

**Comment by grimfang4** [comment]
Hey Mason, thanks for suggesting that.  It's a very important feature for really effective shader usage.  The good news is that it is already implemented (though the documentation of a lot of features is lacking, so I understand missing it)!

You can set up multiple textures with GPU_SetShaderImage().  GPU_Blit() automatically assigns the given image to texture unit 0, so you can assign additional textures if you have the sampler's uniform location:
    GPU_SetShaderImage(image2, image2_loc, 1);
    GPU_Blit(image, NULL, screen, x, y);  // Both image and image2 will be available to the shader

Under the hood, GPU_SetShaderImage() sets the sampler value and binds the texture to the given image unit via glActiveTexture().

**Comment by masonwheeler** [comment]
That's great, except that `GPU_Blit` still only takes a single `src_rect`.  For multitexturing, you need one `src_rect` per source image.

**Comment by grimfang4** [comment]
Yep, that's the issue.  If you need different texture coordinates for the additional images, then you have to do that yourself with uniforms or attributes...  I'll think a bit on if I can provide a better interface for that, but most likely it wouldn't be good to have to make assumptions about the shader's variables.

**Comment by masonwheeler** [comment]
Probably the simplest way would be something like:

    DECLSPEC void SDLCALL GPU_MultitextureBlit 	( 	GPU_Image *  	images,
    		GPU_Rect *  	src_rects,
    		int 	src_count,
    		GPU_Target *  	target,
    		float  	x,
    		float  	y 
    	) 	

and document that calling this will rebind the higher-number textures as if `GPU_SetShaderImage` had been called.

**Comment by grimfang4** [comment]
Yeah, that's the best way for the C interface, but the shader side would probably be forced to follow a convention for how the src_rect texture coordinates are stored...

**Comment by grimfang4** [comment]
Any further thoughts on that?  I think even if it only works for shaders which follow a specified convention for texcoords, it would still be worthwhile for the benefit to the interface.  I might prefer that it be a variation of the more general GPU_BlitTransformX instead of GPU_Blit.

**Comment by masonwheeler** [comment]
...or both.  The extra flexibility is nice, but most of the time you won't need it and so it's good to have the simpler API available.

The one thing that bugs me, though, is that to use an updated SDL_GPU with this new functionality... I would have to use an updated SDL_GPU, and that means losing access to the batch blit functions.  :(

**Comment by grimfang4** [comment]
I would definitely keep GPU_SetShaderImage for cases when that's all you need.

Before I removed the blit batch functions, I first reimplemented them on top of GPU_TriangleBatch.  When I did remove them, I preserved the logic of those functions in the blit-batch test program.  You can find the necessary enums and implementations in tests/blit-batch/main.c.  Hopefully that helps. :)

**Comment by grimfang4** [comment]
Yeah, sometimes I worry about the API growing in exponential steps.  There are 5 normal blit functions, so if I do multitexturing for more than 1, I feel like I should do all 5.

**Comment by masonwheeler** [comment]
> Hopefully that helps. :)

It would be quite helpful if the end-user was programming in C, but this is frequently not the case...

**Comment by grimfang4** [comment]
Oh right...  Sorry about that.  I'm not able to stabilize other language bindings while SDL_gpu itself is in unstable development.

**Comment by masonwheeler** [comment]
Sure, and I don't think anyone would expect you to.  But saying "yes, this functionality that used to be available but was now removed isn't really removed because it's in this external code over here and so you can still use it" doesn't really help anyone who's maintaining their own language bindings.

**Comment by masonwheeler** [comment]
Any progress on this?

**Comment by grimfang4** [comment]
Not yet, but I think it should be in the next release, and there have been so many important changes that such a release will be very soon.  I'm expecting between a week and a month for 0.12.0.

**Comment by masonwheeler** [comment]
One other thing I noticed.  Is there any equivalent of the `SDL_RendererFlip` enum that `SDL_RenderCopyEx` uses to draw a sprite mirrored?  I see APIs for rotation, but nothing for mirroring.

**Comment by grimfang4** [comment]
The equivalent for image flipping would be to scale by -1.  Something like this to flip horizontally: GPU_BlitScale(image, NULL, screen, x, y, -1, 1)

**Comment by grimfang4** [comment]
:-/ I think GPU_MultitextureBlit is a no-go for now.  There are two complications that I haven't figured out.  One, I would need to know the sampler locations for each image.  Two, I would need to know the attribute locations of each set of texture coords...  and GLES 2 and GL 3.1 (AFAIK) don't support attribute arrays.

**Comment by masonwheeler** [comment]
Any particular reason why the API couldn't take those values as inputs?

**Comment by grimfang4** [comment]
As I see it now, it would have to.  But that complicates what was meant to be a simplifying function.  It would need something like an extra array of sampler locations and another array of texcoord locations.  This problem is somewhat similar to what I had when I added GPU_ShaderBlock.  So maybe a helper function that sets up the multitexture locations with a new object type?

Here's an idea of how that might look:
// When loading the shader...
const char* image_names = {"sampler1", sampler2"};
const char* texcoord_names = {"texcoord1", "texcoord2"};
GPU_MultitextureBlock locations = GPU_LoadMultitextureBlock(2, image_names, texcoord_names);

// When rendering...
GPU_SetMultitextureBlock(locations);
GPU_MultitextureBlit(images, src_rects, target, x, y);  // count can be stored in the block

**Comment by masonwheeler** [comment]
Yeah, that looks like a good idea.  I don't actually see this as a *simplifying function* so much as an *enabling function*, making it possible to do something that was not otherwise possible in SDL_GPU without dropping into raw GL.  (Which is how I'm currently handling it, in an extremely hacky and non-portable way.)

**Comment by NicolasPerdu** [comment]
An implementation of SDL_SetWindowIcon for SDL_gpu, something like GPU_SetWindowIcon(GPU_Target *target, GPU_Image *icon)

**Comment by grimfang4** [comment]
I had to make a split somewhere between SDL and SDL_gpu and the non-rendering window interface is beyond that split.  You can get the window ID via GPU_GetContextTarget()->context->windowID, so you can do either:
SDL_SetWindowIcon(SDL_GetWindowFromID(windowID), icon);  // SDL 2.0
or
SDL_WM_SetIcon(icon, NULL);  // SDL 1.2

Those use an SDL_Surface* for the icon.  You can use GPU_LoadSurface() to load a file into a surface or use GPU_CopySurfaceFromImage() if you want to use a GPU_Image that you may have rendered to.

**Comment by grimfang4** [comment]
In other words:
```
void SetWindowIcon(GPU_Target* target, GPU_Image* icon)
{
    if(target == NULL || target->context == NULL)
        return;
    
    SDL_Surface* surf = GPU_CopySurfaceFromImage(icon);
    SDL_SetWindowIcon(SDL_GetWindowFromID(target->context->windowID), surf);
    SDL_FreeSurface(surf);
}
```

**Comment by NicolasPerdu** [comment]
Thank you for your explanation, I didn't know I could get the window with SDL_GetWindowFromID(target->context->windowID)

**Comment by grimfang4** [comment]
No problem. ;)

**Comment by damasko** [comment]
I was looking the same feature a few days ago... thanks.

**Comment by grimfang4** [comment]
It's been way too long since the last release, so I'll try packing one up soon.  A lot of changes have happened and some expected ones haven't.  We can keep building on that.
