### ISSUE TITLE
Pixel "rounding" issue occurring with SNAP_NONE + FILTER_NEAREST

### ISSUE THREAD

**Issue by Serenitor** [grimfang4/sdl-gpu#100]
I wish to use both GPU_SNAP_NONE for smooth scrolling and GPU_FILTER_NEAREST for sharp pixel rendering. However when combining the two, artifacts show up on certain render positions.

Here's a demonstration where you see the exact same image being rendered two times, the only difference being a small offset in their positions. Obviously on the left it shows up broken and on the right it shows up how it's supposed to.

![Render artifact](http://img.r00t.li/renderartifact2.png)

This seems to occur when the position is very close to .5

Here's a little test case you can use to reconstruct this:

```c
GPU_Target* target = GPU_Init(640, 360, 0);
SDL_Surface* surface = GPU_LoadSurface("test.png");
GPU_Image* image = GPU_CopyImageFromSurface(surface);

float offsetA = 100.0;
float offsetB = 100.0;

GPU_SetSnapMode(image, GPU_SNAP_NONE);
GPU_SetImageFilter(image, GPU_FILTER_NEAREST);

while (true)
    {
    GPU_Clear(target);
    GPU_Blit(image, NULL, target, offsetA, offsetA);
    GPU_Blit(image, NULL, target, offsetB + 200.0, offsetB);
    GPU_Flip(target);
    SDL_Delay(100);

    offsetA += 0.5;
    offsetB += 0.48;

    if (offsetA >= 200.0) break;
    }

GPU_Quit();
```

and the image I used:
![Test image](http://img.r00t.li/test.png)

**Comment by grimfang4** [comment]
With GPU_NEAREST, you won't get subpixel smooth motion, as the pixels have to alias.  It's possible that the GL driver rasterizer is just not choosing the right "nearest" pixels when the nearest pixels are equidistant (0.5).  If your image has even dimensions, this will happen without snapping.  This is one of the situations that the snap modes are intended to fix, if there isn't another reason not to use them.  Can you use GPU_SNAP_DIMENSIONS?

**Comment by Serenitor** [comment]
Ah, thank you. But hmm, then I need to figure out what's the best compromise.
Unfortunately GPU_SNAP_DIMENSIONS doesn't seem to make a visible change.
Only with GPU_SNAP_POSITION does the issue disappear, but I'd rather deal with it than to loose subpixel scrolling.

In the game I am working on, I am rendering a grid of tiles and the issue causes them to sometimes shift by 1 pixel and to make these nasty lines appear. 

![Test image](http://up.r00t.li/20171117_game_ykb6.png)

If nothing else helps, maybe I should render the tiles at integer positions on larger images first, and then render those images in subpixel positions to minimize the occurrence of those lines.
