### ISSUE TITLE
Question about z order

### ISSUE THREAD

**Issue by kirilledelman** [grimfang4/sdl-gpu#101]
Jonathan,

I was wondering what should I do, if I want to control sprite z-index.

In my setup, I'm using matrix transforms together with your GPU_Blit method's to position and render my sprites. My matrices allow me to transform sprites hierarchically, and GPU_Blit's transform parameters let me "fine tune" positioning - i.e. center sprites at local origin, flip it, or use rotated sprite sheets. Works awesome.

I'd love to be able to control sprite "height", or draw order, or z coordinate in my matrix step. I tried changing z coordinate in my transform, but it didn't seem to work. Is there anything I can do, turn on depth check, or write, or something to make it happen?

Thanks again for a great library.

**Comment by grimfang4** [comment]
I just added some initial depth buffer support in e1b1b5112518b47828ca7a17997b27663af2d83c.  Just call `GPU_SetDepthTest(screen, 1)` and it should work.  Only context targets (e.g. what you get from GPU_Init()) have depth buffer attachments, but I'll add a function later to add them to image targets.

Do try this with changing the z coordinate in your transform and tell me if you need any other functionality.  The built-in ortho projection's near and far planes are (-100, 100), which seems to work fine, but if you need to adjust them, GPU_Camera now has those members.  You can adjust them directly on the `screen->camera` (for now).

**Comment by grimfang4** [comment]
Depth buffers for image targets can be added via GPU_AddDepthBuffer() as of a1342fc66da092952c03263df8beacad4e7e0e1a.

**Comment by kirilledelman** [comment]
You rock. I'll try it out!
