### ISSUE TITLE
GPU_Quit being done automatically?

### ISSUE THREAD

**Issue by Serenitor** [grimfang4/sdl-gpu#103]
A couple of days ago I compiled the up to date version of SDL_gpu, but since then my application does no longer terminate gracefully when clicking the X button on the window GUI (I'm not sure if it's caused by the SDL_gpu update or by changes I made to my own architecture).
For example, the game crashes in the last frame it tries to render since the textures are already freed.
Also, when I call GPU_Quit() manually after the SDL_QUIT event fired I get a crash.

Could it be that GPU_Quit is somehow implicitly called by the SDL_QUIT event? If so, how can I prevent this? I'd like to do the cleaning up myself as the application isn't necessarily terminated through the SDL_QUIT event.

Tested on Win10x64.

**Comment by grimfang4** [comment]
There's no implicit connection to that event.  If you destroy the window or something like that, there will be trouble.  Can you provide some code and I'll see if there's something I can help with?  You could verify the issue by reverting back to an older SDL_gpu to check.

**Comment by Serenitor** [comment]
Yea, of course it was my mistake; after not working for a couple of days on the project I failed to make the connection with a change I made to the window handling. Everything good now, thanks for the hint.
