### ISSUE TITLE
Virtual resolution miscalculation on Y-axis

### ISSUE THREAD

**Issue by Serenitor** [grimfang4/sdl-gpu#104]
Either I don't quite understand the virtual resolution system after all, or there's a bug here.

Let's get right to it:

```cpp
int main ()
    {
    GPU_Target* windowTarget = GPU_Init(1280, 720, 0);
    GPU_SetVirtualResolution(windowTarget, 640, 360);

    GPU_Image* imageDst = GPU_CreateImage(512, 512, GPU_FORMAT_RGBA);
    GPU_Target* imageDstTarget = GPU_GetTarget(imageDst);
    GPU_SetSnapMode(imageDst, GPU_SNAP_NONE);
    GPU_SetImageFilter(imageDst, GPU_FILTER_NEAREST);
    GPU_SetAnchor(imageDst, 0.5, 0.5);
    GPU_SetVirtualResolution(imageDstTarget, 256, 256);
    GPU_SetImageVirtualResolution(imageDst, 256, 256);

    GPU_Image* imageSrc = GPU_LoadImage("test.png");
    GPU_SetSnapMode(imageSrc, GPU_SNAP_NONE);
    GPU_SetImageFilter(imageSrc, GPU_FILTER_NEAREST);
    GPU_SetAnchor(imageSrc, 0.5, 0.5);

    while (true)
        {
        GPU_Clear(windowTarget);
        GPU_ClearColor(imageDstTarget, GPU_MakeColor(0, 191, 64, 255));

        GPU_Blit(imageSrc, NULL, imageDstTarget, 128.0, 128.0);
        GPU_Blit(imageDst, NULL, windowTarget, 320.0, 180.0);

        GPU_Flip(windowTarget);
        SDL_Delay(2000);
        break;
        }

    GPU_Quit();

    return 0;
    }
```

What I expect:

![Test image](http://up.r00t.li/20171218_G9cD1ZyB.png)

What I get:

![Test image](http://up.r00t.li/20171218_CM3uKTDa.png)

Image used:

![Test image](http://img.r00t.li/test.png)

My understanding is that changing the resolution of imageDst in GPU_CreateImage shouldn't have any effect on the placement of imageSrc as the virtual resolutions and anchors remain unchanged. Yet, it does have an effect as demonstrated by the screenshots - however, only on the Y-axis. This seems fishy.

**Comment by grimfang4** [comment]
Looks like my commit auto-closed this.  Can you verify that things are working now on your end?

**Comment by grimfang4** [comment]
So, the problem (internally) seems to have been using the wrong height when flipping coordinates for rendering to image targets.  What you're doing looks right.

**Comment by Serenitor** [comment]
With that, the little test case I wrote now works as expected. Thanks!
Sadly however, my actual project now crashes as for some reason I can no longer read context->windowID from the target returned by GPU_Init(). Probably not connected to this commit I figure?

**Comment by grimfang4** [comment]
Yeah, not related to this commit.  Try deleting your intermediate (object) files and recompile everything to make sure there's not a stale object being linked.  If nothing changes, definitely open a new issue.
