### ISSUE TITLE
Failed to attach depth buffer to target.

### ISSUE THREAD

**Issue by kirilledelman** [grimfang4/sdl-gpu#106]
Jonathan,

The new depth functions work well when I run my code on a Mac ( I think it's using OpenGL 3 implementation ). However, when I'm running the same code on Raspberry Pi ( GLES 2.0 ), I get "Failed to attach depth buffer to target." error from GPU_AddDepthBuffer. Looks like attaching depth buffers to targets is not supported on RPi's VC4 chip.

Do you know of any workarounds I could employ, in my quest of drawing sprites in order of their z-coordinate? Other types of buffers, or anything? I'm using my own shaders to draw sprites.

Also, I found that if I even call GPU_AddDepthBuffer on RPi ( and it returns false ), nothing can be drawn afterwards, as if the target is left in some invalid state.

Thanks!

**Comment by kirilledelman** [comment]
Actually, I saw something online that may fix this:

https://stackoverflow.com/questions/44343363/opengl-es-2-0-gl-depth-component-and-glteximage2d

Suggests to use GL_DEPTH_COMPONENT16 in place of GL_DEPTH_COMPONENT on GLES2.0

I've modified your source locally in `renderer_GL_common.inl`:
Modified line 1985 to:

`glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT16, target->base_w, target->base_h);`

and now it lets me attach depth buffer and depth test/z coord works correctly on Raspberry Pi!

I'm not sure how this affects other platforms.

**Comment by grimfang4** [comment]
I think that’s probably right and it’s a common error to use GL_DEPTH_COMPONENT.  I’ll commit that fix tomorrow!

**Comment by grimfang4** [comment]
This should be resolved in 5dfac56e3573156e128e3bee69c98b97831d8e7a.
