### ISSUE TITLE
GL_POINTS and more

### ISSUE THREAD

**Issue by kirilledelman** [grimfang4/sdl-gpu#107]
Jonathan,

I was wondering if you have any plans to include GL_POINTS drawing commands in the future?

It would be great, if one could draw a number of particles from a buffer of x, y coords (like you do with render polygon primitive), and include extra per-particle attributes for shader, like per-particle opacity, scale, rotation, or color. You don't have to write the shaders themselves, just have methods for passing these extra params.

My intention is to use SDL_GPU to render http://google.github.io/liquidfun/ particles on Raspberry Pi - great for rendering mixing liquids of different colors etc.

I think it would be a great asset to an already must-have library for SDL.

Thank you.

**Comment by grimfang4** [comment]
Yeah, someone else has asked about this before, too.  It would be a good idea to add even rough support for other primitives.  I'll see what it should look like, but it'd probably be similar to GPU_TriangleBatch(), but called something like GPU_PrimitiveBatch().

**Comment by grimfang4** [comment]
Alright, looks like the changes were simple enough.  I've added GPU_PrimitiveBatch() and a set of primitives to use.  I don't have a test program set up for it, so you'll have to see if it works as you expect for now.

**Comment by kirilledelman** [comment]
Awesome stuff, Jonathan. Thank you for your work. I'll let you know if something isn't quite working.
