### ISSUE TITLE
How to lock Image?

### ISSUE THREAD

**Issue by pistacchio** [grimfang4/sdl-gpu#110]
Is there a way to manipulate (read / write) an image pixel by pixel or update with pixel data like SDL_Lock / Unlock?

**Comment by grimfang4** [comment]
There's not really a direct comparable function for SDL_LockTexture(), which is for write-only access to arbitrary backing data.  The closest thing would be using GPU_CopySurfaceFromImage() and GPU_UpdateImage() or else keeping your own pixel buffer and using GPU_UpdateImageBytes().
