### ISSUE TITLE
Set Window Title?

### ISSUE THREAD

**Issue by jkstpierre** [grimfang4/sdl-gpu#111]
Is there a way to set the title of the window?

SDL2 allowed for it via the SDL_CreateWindow(...) method.

Thanks!

**Comment by grimfang4** [comment]
Yep!  SDL_gpu only replaces the rendering of SDL.  The window handling is still done the same way.  You can access a context target's (e.g. the screen's) windowID with something like `screen->context->windowID` and change the title like `SDL_SetWindowTitle(SDL_GetWindowFromID(screen->context->windowID), "A new title");`.

**Comment by jkstpierre** [comment]
Awesome thanks!!
