### ISSUE TITLE
Depth testing

### ISSUE THREAD

**Issue by kirilledelman** [grimfang4/sdl-gpu#112]
Jonathan,

I'm using 
```
GPU_SetDepthTest( target, true );
GPU_SetDepthWrite( target, true );
target->camera.z_near = -65535;
target->camera.z_far = 65535;
```
to help override "drawing order" of certain sprites in my application. (Yes, I'm aware of blending artifacts when drawing transparent sprites in reverse order)

In my engine, I draw hierarchy of sprites - parent first, then children, then grandchildren. In the basic case, they all have z coordinate = 0. When depth write, and testing is enabled, it looks like the parent is always drawn last, on top of children (even though the actual drawing order is the opposite). I suspect the depth testing is "greater than" instead of "greater or equal", or something along those lines. When I turn off depth testing, they are drawn correctly.

Could you add the ability to alter the depth testing function, or change its default type?

It would also be great if there wasn't a hard limit on camera z_near/z_far being in -100/100 range.

Thank you.

![depth](https://user-images.githubusercontent.com/6539713/34909539-9b9ef62a-f868-11e7-865a-26b414813fad.jpg)

**Comment by kirilledelman** [comment]
I've added gl.h to my test project to confirm that this is the issue. (I don't want to leave that in though). I'd like objects sharing z coordinate to overwrite each other in the order drawn, greater z values being forced "in front", and smaller "behind". I think the default `glDepthFunc` just needs to be switched to `GL_LEQUAL`. 

![lequal](https://user-images.githubusercontent.com/6539713/34960670-727e2186-fa01-11e7-983c-317c966d910f.jpg)

**Comment by grimfang4** [comment]
Yep, I can add something to change the depth test.

**Comment by kirilledelman** [comment]
Great! Thank you.

**Comment by kirilledelman** [comment]
Hi, has there been a commit to fix this yet?

**Comment by grimfang4** [comment]
Recent job change has me busy!  This latest adds a function to change the depth test.  The z range of the depth buffer should be affected by the target camera's z_near and z_far values.

**Comment by kirilledelman** [comment]
Thank you, Jonathan. Good luck on the new job!
