### ISSUE TITLE
DinoMage WordPress issues

### ISSUE THREAD

**Issue by NuklearBomb** [grimfang4/sdl-gpu#119]
I'm running Firefox 58.0.1 64-bit on Debian Jessie. Browsing the WordPress site DinoMage, I'm having issues where Firefox will say "A website is slowing down Firefox, what would you like to do?", and cases where pages won't load, Firefox instead displaying this:

```
Content Encoding Error

The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.

Please contact the website owners to inform them of this problem.
```

On one page in particular (http://www.dinomage.com/2015/01/sdl_gpu-simple-tutorial/), I am getting a complete system crash. Firefox's CPU/memory usage both go through the roof, the entire system stops responding, and I have to turn the computer off by holding the power button. This happens every single time without fail, even on a version of the page I downloaded. The page works fine only when I disable Javascript in Firefox's `about:config` tab.

Having done some of my own investigating, I have narrowed the problem down to the `minify` WordPress plug-in that is being used on the page. I deleted all references to `http://www.dinomage.com/wp-content/cache/minify/*` on a copy of the page I downloaded and the issue has disappeared.

I'm not sure what features of `minify` you are using, but I _highly_ suggest disabling it. Or, at the very least, updating it to a more stable version.

**Comment by grimfang4** [comment]
Thanks for reporting this.  I'll update things.
