### ISSUE TITLE
Expose texture handles with a function

### ISSUE THREAD

**Issue by Wizzard033** [grimfang4/sdl-gpu#120]
Since SDL_gpu does my image loading, I was wondering if a convenient GetHandle function could be added to get a texture handle without me depending on an IMAGE_DATA structure cast.

**Comment by AnthonySuper** [comment]
This would be very helpful to me as well!

**Comment by grimfang4** [comment]
Yeah, I think this is reasonable.  There are several things that could be exposed in the future, but I'd want to make sure they can be exposed in a way that is GL API neutral.

Note: Texture handles in OpenGL are GLuint, but both D3D and Vulkan use pointers.  The neutral type to do both would be uintptr_t and that reinforces dependency on C99.

**Comment by grimfang4** [comment]
Also, ideally there'd be a way to either inform SDL_gpu of changes you made to the texture, tell it to check for changes itself, or forget about the texture.  This would need another function some time in the future.

**Comment by Wizzard033** [comment]
For now, I'm just hoping to use the textures loaded, because I exclusively use SDL_gpu for that. It'd suffice to leave a comment that modifying the texture via the handle will cause problems.

**Comment by grimfang4** [comment]
Added GPU_GetTextureHandle() in 0a468edf7289d4b4fbebbf1dca6747cd76a65710.
