### ISSUE TITLE
where does framerate get throttled to 60 fps?

### ISSUE THREAD

**Issue by michaeladamkatz** [grimfang4/sdl-gpu#126]
I'm running some of the demos on Windows. It appears that fps is being throttled to 60 fps. I'm trying to understand where this is happening. When I comment out the call to `GPU_Flip(screen);` in the demo main loop, it greatly increases the fps, to like 4000. I realize that this makes sense because so much of the actual work is done in `GPU_Flip(screen);` However, it seems like too much of a coincidence that when `GPU_Flip(screen);` is used the program runs at exactly 60 fps in both debug and release build. So I thought there must be some throttling in that function. But stepping into it, I can't see where. Any ideas?

**Comment by koniin** [comment]
Try setting GPU_INIT_DISABLE_VSYNC in your preinit flags (before GPU_Init). 
`
GPU_SetPreInitFlags(GPU_INIT_DISABLE_VSYNC);
screen = GPU_Init(800, 600, GPU_DEFAULT_INIT_FLAGS);
`

**Comment by michaeladamkatz** [comment]
Thanks for the information.

So the answer to my question is that the throttling happens way down at the opengl driver level, where it waits to swap buffers until a vsync event happens.

https://www.khronos.org/opengl/wiki/Swap_Interval

**Comment by grimfang4** [comment]
The magic value of 60 fps is a hint that your GL driver is synchronizing with the display refresh rate (vsync).  This is a platform-specific setting that SDL manages and it's up to the GL driver to enforce or not.

Yes, SDL_gpu tells SDL how to handle vsync by default according to the preinit flags.  If you want to change it for any current GL context, you can use SDL_GL_SetSwapInterval() in SDL 2.
