### ISSUE TITLE
Blit screen target to other target or caprute screen

### ISSUE THREAD

**Issue by dhiahassen** [grimfang4/sdl-gpu#130]
The screen target does not have an image , or for `screen` object the field `GPU_Traget::image` is set to null  , to capture the screen and save it to filesystem , a workarround would be : 
 `GPU_SaveImage (GPU_CopyImageFromTarget(screen))` 
 ( ofcouse with saveing a pointer to the image to free it ) 
i am thinking of a new feature , that is `GPU_BlitTarget` like the following : 
```
void GPU_BlitTarget (GPU_Target * target,GPU_Target * dist)
{ 
    if (target == NULL) ...
   if (target == target->context->target) // this is the context target , the screen
{
   GPU_Image * tmp = GPU_LoadImageFromTarget (target);
   GPU_Blit(tmp , dist , ...)
   GPU_FreeImage(tmp);
}else
{
  GPU_Blit( target->image , dist ... );
}
}

```

That would be a cross-target blit , allows the user to bypass checking if the target's image is valid ..

**Comment by grimfang4** [comment]
This is certainly useful and is good to have here as a reference, but probably not a good fit for SDL_gpu's design.  It is easy for users to expect built-in functionality to have reasonable performance characteristics, but this in particular could be very slow (frame buffer read and allocations) and discourage users from implementing a more reasonable app-specific approach of caching the target's image data.

**Comment by dhiahassen** [comment]
I can't agree more
