### ISSUE TITLE
MSVC 2015 defines snprintf

### ISSUE THREAD

**Issue by aquileia** [grimfang4/sdl-gpu#14]
To compile under Visual Studio 2015, the
`#ifdef _MSC_VER`
in SDL_gpu_matrix.c#L25 and renderer_GL_common.inl#L39 has to be replaced by
`#if defined(_MSC_VER) && (_MSC_VER < 1900)`
because it defines snprintf by itself now.

Originally reported by @chisquare130 over at wesnoth/wesnoth

**Comment by grimfang4** [comment]
This is fixed in the latest commit.  Thanks!
