### ISSUE TITLE
Having problems enabling MSAA

### ISSUE THREAD

**Issue by SSYGEN** [grimfang4/sdl-gpu#143]
Hello, I'm sorry to bother you @grimfang4 but I'm having some trouble enabling MSAA with SDL-gpu and I was wondering if you could shed some light into it.

I'm following the way people say to do it in SDL as well as what was mentioned in this issue https://github.com/grimfang4/sdl-gpu/issues/75 by doing this:

```c++
SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS, 1);
SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, msaa);

window = SDL_CreateWindow("", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, screen_width, screen_height, SDL_WINDOW_OPENGL);
GPU_SetInitWindow(SDL_GetWindowID(window));
screen = GPU_Init(screen_width, screen_height, 0);
```

(if you want to look at the code with some context https://github.com/SSYGEN/AIKA2D/blob/master/aika.cpp#L2438)

But it doesn't seem to work. I couldn't figure out what I'm doing wrong since this seems to be the way that people say to do it in SDL as well (use `SDL_GL_SetAttribute` before creating the window).

Everything draws fine and the program runs, but it doesn't draw shapes or images in an anti-aliased manner like it should. Calling `SDL_GL_GetAttribute` and printing the values of `SDL_GL_MULTISAMPLEBUFFERS` and `SDL_GL_MULTISAMPLESAMPLES` returns expected values (1 and the MSAA level set).

Any ideas on what might be happening? Thanks and sorry to bother you.

**Comment by Slipyx** [comment]
I remember when I was having troubles getting this to work as well. I discovered that it would only work if I called SDL_Init _before_ GPU_Init. I see you're doing that too though. Also not entirely sure if necessary, but I did call glEnable( GL_MULTISAMPLE ) after setting the SDL attributes. Also, MSAA doesn't work for image targets (FBOs), so make sure that's not the case.
