### ISSUE TITLE
question about render-to-image, especially "uploading" to GPU

### ISSUE THREAD

**Issue by michaeladamkatz** [grimfang4/sdl-gpu#146]
Render-to-image is working for me, but I wanted to make sure I understand it. The code below shows how I'm using it. Please correct any incorrect comments in the code.

My main question is: With a previous GPU library, I had to "upload" the image to the GPU before the GPU could use it. So I'd allocate the image and its pixels, do whatever drawing to those pixels, upload it to the GPU, and then use it to draw to the screen. If I wanted to further modify the image, I'd do the modification back on the CPU, and upload it again. For sdl-gpu, is the rendered-to image's target always "uploaded to the GPU" and drawing on it happens on the GPU? It could be that the previous library I used couldn't do this because it was trying to support some GPUs or APIs where you can't modify a texture once it's on the GPU.

1. Create the image you want to render to:
```
// allocate the image structure but not the actual pixels
GPU_Image *spriteImage = GPU_CreateImage( width, height, GPU_FORMAT_RGBA );
// allocate the pixels
GPU_LoadTarget( spriteImage );
// make the pixels transparent to start
GPU_Clear( spriteImage->target );
```

2. Draw whatever you want on the image, in this case an atlas sprite image.
```
GPU_Image *atlasImage; // loaded earlier from a disk file
GPU_Rect sourceRect; // set to something appropriate on your atlas image
GPU_Blit( atlasImage, &sourceRect, spriteImage->target, x, y );
```

3. Use the rendered image, in this case drawing it on the screen.
```
GPU_Blit( spriteImage, NULL, screen, x, y );
```

4. When you don't need the rendered image and more, free it, including the pixels of its target.
```
// frees both the image structure and the target pixels
GPU_FreeImage( spriteImage );
```

**Comment by grimfang4** [comment]
Yep, that's about right.

SDL_gpu uses an SDL_Surface as the software/RAM/CPU-side intermediary for GPU textures.  You can load an SDL_Surface (e.g. with  GPU_LoadSurface()), manipulate it pixel-by-pixel, then upload it with GPU_CopyImageFromSurface().  When you use GPU_LoadImage(), it does those two steps together so you don't have to manage the RAM copy.  There are functions for updating the contents of a GPU_Image from an SDL_Surface.

SDL_gpu exposes render targets so you can indeed modify textures on the GPU.  GPU_Images are always on the GPU and GPU_Targets are how you render onto them.  One of the goals of SDL_gpu is to do as much work as possible on the GPU, but do it transparently and with the same workflow as with software rendering.

I would modify the first two comments.  GPU_CreateImage() allocates and initializes the texture and its pixel storage.  GPU_LoadTarget() creates a render target associated with the given image for modifying those pixels through subsequent calls.

**Comment by michaeladamkatz** [comment]
Thanks. Not sure whether GPU_PrepareTarget() would be a better name. And it doesn't make sense just to automatically set up a render target for all images because there is time/space overhead?

**Comment by grimfang4** [comment]
Yes, it makes extra calls to the driver to allocate a framebuffer object (FBO).  GPU_LoadTarget() was used just because it implies some work, that you need a starting point (the image), it can be used in some way similar to GPU_LoadImage(), and that it fails similarly.
