### ISSUE TITLE
sdl-gpu looking for SDL2.dll in debug build

### ISSUE THREAD

**Issue by jesta88** [grimfang4/sdl-gpu#147]
I'm on Windows and I installed SDL2 through vcpkg. The SDL2 shared library for debug builds is named SDL2d.dll, and SDL_gpu seems to be looking for SDL2.dll even on debug configuration.

If I switch to release there's no problem. I'm not an expert with CMake installs but maybe someone could point me in the right direction? I want sdl-gpu to look for SDL2d.dll on debug configuration.

**Comment by jesta88** [comment]
Where should I put this? In FindSDL2.cmake?

**Comment by grimfang4** [comment]
@ras0219-msft 's suggestion seems like a good, comprehensive solution, but I'm not in a position to test it all out.  I'm closing this due to the merge of @jesta88 's interim solution.
