### ISSUE TITLE
Add SDL2d to the searched libraries

### ISSUE THREAD

**Issue by jesta88** [grimfang4/sdl-gpu#148]
https://github.com/grimfang4/sdl-gpu/blob/dd982b9c7af9f9f7c8806d20cf29ff348f8ab937/scripts/FindSDL2.cmake#L35

On some platforms, SDL2 builds SDL2d.dll in debug mode, which can't be found by sdl-gpu. 

This would fix #147

**Comment by grimfang4** [comment]
Merged fix in 2c9da815515a7e88c372f5089933f856c0566e26
