### ISSUE TITLE
Unable to initialize a renderer on an external window

### ISSUE THREAD

**Issue by masonwheeler** [grimfang4/sdl-gpu#15]
SDL2 allows you to call `SDL_CreateWindowFrom()` on an existing GUI object's window handle, and then create a renderer on it.  This technique doesn't appear to migrate well to SDL_GPU.
- Create a Windows form
- Create a control on it and obtain its HWND
- Create an `SDL_Window` on that HWND with `SDL_CreateWindowFrom`.
- Call `SDL_GetWindowID` on this window and `GPU_SetInitWindow` on the result
- Call GPU_Init

Expected: A working renderer
Observed: GPU_Init fails.  Could not initialize.

A bit of digging reveals that this happens because GLEW could not retrieve the version string, because SDL_GPU failed to initialize the first GL context before calling `glewInit`.  After doing this manually on my end, GPU_Init now throws an access violation in the call to `applyTargetCamera` because `GPU_GetContextTarget` returns null.

As near as I can tell, this is returning null because earlier on, in the call to `MakeCurrent,` `target->context->context` is null and so the required initialization never takes place.  I haven't been able to determine yet what's missing that's causing `target->context->context` to be null at this point.

**Comment by masonwheeler** [comment]
On further investigation, `target->context->context` is null because `SDL_GL_CreateContext` found that the window did not contain the `SDL_WINDOW_OPENGL` flag.  This just keeps getting messier.

**Comment by grimfang4** [comment]
That makes sense at least.  Does SDL detect the PFD_SUPPORT_OPENGL pixel format descriptor flag and put SDL_WINDOW_OPENGL in there?

**Comment by masonwheeler** [comment]
Nope.  According to the source, the only way to put `SDL_WINDOW_OPENGL` on a foreign window is with an obscure hint that has it copy the pixel format of a pre-existing SDL_Window, which is kind of pointless because the whole point of using a foreign window is that you're *not using* SDL's window creation mechanism.

I [posted a request to the mailing list](http://lists.libsdl.org/pipermail/sdl-libsdl.org/2015-August/098614.html) for a new hint that will allow you to explicitly set up foreign windows with OpenGL support.  After making this change locally and rebuilding SDL2, I'm able to create a working SDL_GPU renderer, although I still have to set up the initial GL context on my side.  This should be handled in-library IMO.

A simple way to do this would be to call `glGetString(GL_VERSION)` before calling `applyTargetCamera` in the initialization.  If it returns a null string, one of two things has happened.  Either the system does not support OpenGL, or (much more likely!) there's no context yet.  Attempt to set up a context on the window currently being initialized, and if that fails, bail out with an error.

**Comment by grimfang4** [comment]
That sounds reasonable.  Is it possible to get the existing SDL_GLContext associated with the SDL window?  SDL_gpu uses the context for certain things.

The only way I see is to use SDL_GL_GetCurrentContext(), which is not specific to a window but we could assume it.  If we can't reliably get the context, then maybe we ought to just always create a new one and not bother checking if glGetString() works.

**Comment by grimfang4** [comment]
It looks like SDL_gpu already forces a call to SDL_GL_CreateContext().  This is done before glewInit(), and applyTargetCamera() (via MakeCurrent()) is called right after that.  So if the context is created successfully with your hint, I'm not yet sure which interaction is failing.

**Comment by grimfang4** [comment]
We'll need to get more info on this in order to follow up.

**Comment by bryanedds** [comment]
Can someone follow up with the workaround for this? This is blocking me from being able to utilize SDL_gpu since my game editor needs to provide a window from Windows Forms.
