### ISSUE TITLE
 GPU_ResetProjection() needed after use of GPU_SetWindowResolution()

### ISSUE THREAD

**Issue by Coldragon** [grimfang4/sdl-gpu#156]
Hi,

I want my window to be resizable, but when I resize it and call GPU_SetWindowResolution, the "target" seem to still have the same size (800 x 480 here) and is just stretched. 
How can I do to change the target resolution and have the origin 0,0 in the uppper left screen ?
I tried lot of thing like editing GPU_Target manually or calling function for virtual resolution or viewport edit but I can't find the proper way to do this.
Thank's

```c
int main(int argc, char ** argv)
{
	SDL_Window * window = SDL_CreateWindow("Test", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 800, 480, SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE);
	GPU_SetInitWindow(SDL_GetWindowID(window));
	GPU_Target * target = GPU_Init(800, 480, SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE);
	GPU_Renderer* renderer = GPU_GetCurrentRenderer();
	GPU_RendererID id = renderer->id;
	printf("Renderer : %s (%d.%d)\n", id.name, id.major_version, id.minor_version);
	GPU_Image * image = GPU_LoadImage("icon.png");
	SDL_Color color = { 200, 50, 30, 255 };

	_Bool quit = 0;
	while (!quit)
	{
		SDL_Event event;
		while (SDL_PollEvent(&event))
		{
			switch (event.type)
			{
			case SDL_QUIT:
				quit = 1;
				break;
			case SDL_WINDOWEVENT:
				switch (event.window.event)
				{
				case SDL_WINDOWEVENT_RESIZED:
					GPU_SetWindowResolution(event.window.data1, event.window.data2);
					break;
				default:
					break;
				}
				break;
			default: 
				break;
			}
		}

		GPU_ClearRGB(target, 50, 50, 50);
		GPU_BlitRotate(image, NULL, target, 50, 50, 180);
		GPU_RectangleFilled(target, 0, 0, 800, 1, color);
		GPU_Flip(target);
	}

	return 0;
}
```

**Comment by grimfang4** [comment]
This may be a bug introduced recently.  Are you using the latest version from Github?  If so, can you see if calling GPU_ResetProjection() after resizing works?

**Comment by Coldragon** [comment]
Thank's for the answer.
It properly resize the Target now thank's but it's not centered
![image](https://user-images.githubusercontent.com/471393/48666883-8f1aed00-eaca-11e8-9118-5b8b5eab9e8d.png)
![image](https://user-images.githubusercontent.com/471393/48666885-993ceb80-eaca-11e8-8385-18551d05a93b.png)
It should be centered ? (the position of the camera is still 0,0)

**Comment by grimfang4** [comment]
After that, it is centered according to (0,0) being the upper left corner and (screen->w/2, screen->h/2) being the center of the view.  If you have an object you want to center on, then you can adjust the camera’s x and y then use GPU_SetCamera().

**Comment by Coldragon** [comment]
Ok i'm just dumb, my object are still blitted in original_screensize_w/2 and original_screensize_h/2 ... I though I blitted them with "world coordinate" 0,0 (like i do with classic sdl) ...

But thank's a lot your first answer fixed the issue. Using GPU_ResetProjection() for that problem is the normal behavior ? I saw that in your test project there were no resizable window.

**Comment by grimfang4** [comment]
Needing GPU_ResetProjection() is a side-effect of a recent change.  If you use a slightly older revision, it isn't necessary.  I'll be putting an update together at some point that makes it unnecessary again.
