### ISSUE TITLE
Static Linking

### ISSUE THREAD

**Issue by jkstpierre** [grimfang4/sdl-gpu#160]
Is it possible to statically link a program using SDL_gpu as opposed to always dynamically linking to it? The reason I ask is because distribution might be more difficult since most end users wouldn't have a copy of the SDL_gpu library on their machines. 

I am on Linux btw.

**Comment by grimfang4** [comment]
Yes it is.  The CMake variable SDL_gpu_BUILD_STATIC is on by default, so you should get libSDL2_gpu.a and libSDL2_gpu.dll.a.

With Visual Studio.  I think there's still a naming collision between the dynamic and static libraries for Visual Studio, so you may have to disable SDL_gpu_BUILD_SHARED or build just the SDL_gpu project in your solution.  Not sure if there are naming collisions on Linux, as I haven't explicitly built there in a little while.
