### ISSUE TITLE
I made a demo of using sdl-gpu with ImGui

### ISSUE THREAD

**Issue by ryancheung** [grimfang4/sdl-gpu#162]
For anyone want to use this project with ImGui, here is a example:

https://github.com/ryancheung/sdl2-gpu-with-imgui

**Comment by dhiahassen** [comment]
nice job :D , if you have any issues with rendring i can help you , i build a game engine studio with an emulator using sdl_gpu + imgui

**Comment by ryancheung** [comment]
@dhiahassen I have a issue in macOS, it seem there's no glsl version 120 support in it, 
And further more, ImGui integrateing with sdl only support opengl 3 or 2 (found in the official imgui example).
So, in macOS, SDL_gpu with ImGui use the OpenGL 3, which shows glsl version 120 not supported.
