### ISSUE TITLE
Unexpected scaling behavior after updating version

### ISSUE THREAD

**Issue by incinirate** [grimfang4/sdl-gpu#166]
Possibly related to #156. After updating to the latest version of sdl-gpu (specifically after 1eb012734247d857905f15f792fcd7a544b863e3), scaling images with GPU_BlitRect or GPU_BlitScale produces very strange behavior. Additionally it seems that the coordinate mode has been reversed, as the image is upside-down. Are these changes (and how to deal with them) documented somewhere?

Before: 
![](https://i.would.download/a-gate.png)
After:
![](https://i.would.download/a-route.png)

I can work around this by using something akin to the following (where target is the `GPU_Target*` of my image that needs to be scaled):
```cpp
GPU_Camera cam = GPU_GetCamera(target);
cam.x -= (scaleFactor - 1)*(imageWidth / 2);
cam.y -= (scaleFactor - 1)*(imageHeight / 2);
cam.zoom_x *= scaleFactor;
cam.zoom_y *= -scaleFactor;
GPU_SetCamera(target, &cam);
```
However, this solution is kind of gross, doesn't make a whole lot of sense, and doesn't work in every case. 

This is the way I am scaling by the way if it helps:
```cpp
GPU_BlitScale(buffer, nullptr, renderer,
    windowWidth / 2, windowHeight / 2,
    scaleFactor, scaleFactor);

GPU_Flip(renderer);
```

Any help is greatly appreciated.

**Comment by ryancheung** [comment]
After some usage of SDL_gpu, I found a way to fix the flip problem:
1. Use physical coordinates for Blit shapes or GPU_Images to screen target.
2. Use math coordinates for Blit a GPU_Image to another GPU_Image

**Comment by grimfang4** [comment]
That sounds consistent with that changeset and should be considered a regression.  Thanks for catching this.

I think the problem is that GPU_ResetProjection() should be acting on a specific target and not always the context target and GetTarget() should use that.

**Comment by grimfang4** [comment]
Could you check if this has been affected by 86296aef0950f096c313ff86fc26dabc2f36bc73?

**Comment by incinirate** [comment]
Everything works as expected now, thank you so much for your work!
