### ISSUE TITLE
GPU_ResetProjection required when using SDL_WINDOW_ALLOW_HIGH_DPI

### ISSUE THREAD

**Issue by earlyriser-** [grimfang4/sdl-gpu#167]
Related to #166 and #156.

After you create a high-DPI window you need to call GPU_ResetProjection() for virtual resolution to work. GPU_GetVirtualResolution() will give you the correct virtual resolution, but GPU_Blit() will require that you use physical coordinates. After calling GPU_ResetProjection(), GPU_Blit() draws to virtual coordinates. I was using a work-around using a scaling factor but this is much simpler.

For an image drawn at ( window->w / 2 , window->h / 2 ):

Without GPU_ResetProjection():
<img width="812" alt="screen shot 2019-01-01 at 2 16 03 pm" src="https://user-images.githubusercontent.com/9757975/50576507-54e28200-0dd0-11e9-9c8c-d979483e9c74.png">

With GPU_ResetProjection():
<img width="812" alt="screen shot 2019-01-01 at 2 16 20 pm" src="https://user-images.githubusercontent.com/9757975/50576514-780d3180-0dd0-11e9-9957-d0ba0a26bf84.png">

Example:

    //Create high-DPI window
    GPU_Target *window = GPU_Init(windowWidth, windowHeight, SDL_WINDOW_ALLOW_HIGHDPI);

    if (window == NULL)
    {
        cout << "could not initialize window" << endl;
    }
    
    //Required to make virtual resolution work
    //with high-DPI
    GPU_ResetProjection();

**Comment by grimfang4** [comment]
Could you check if this has been affected by 86296aef0950f096c313ff86fc26dabc2f36bc73?

**Comment by earlyriser-** [comment]
Yep, that worked! Erased all calls to GPU_ResetProjection() and everything works perfectly. 
Thanks for the reply -- sorry it took me so long to get back to you.

**Comment by grimfang4** [comment]
No problem at all.  I'm glad we got this part resolved.
