### ISSUE TITLE
rendering to image results in downscaled and flipped image

### ISSUE THREAD

**Issue by damiano-massarelli** [grimfang4/sdl-gpu#170]
Hello there,
I'm trying to render an image onto another image. I'm using the following code (sort of)
```
GPU_Image* offscreen= GPU_CreateImage(width, height, GPU_FORMAT_RGBA);
GPU_GetTarget(offscreen);
...
GPU_Blit(someImage, nullptr, offscreen->target, x, y);
```
However, `someImage` is rendered upside down and downscaled. I'm probably doing something wrong. Is there a way to render some image with the right orientation and in a way that its original dimensions are kept? Thanks!

**Comment by damiano-massarelli** [comment]
ok, looking a bit more in depth it seems like this is the same issue as the one reported here #168. I also tried to disable the camera on `offscreen->target` but nothing changes. I will wait for news on the older issue. Thanks again.

**Comment by grimfang4** [comment]
It is likely the same problem.  Could you check if this has been affected by 86296aef0950f096c313ff86fc26dabc2f36bc73?

**Comment by damiano-massarelli** [comment]
I'm glad to say that it is now working fine. This is the code I used (hope it can be useful as a reference)
```
#include <SDL.h>
#include <SDL_gpu.h>

int main(int argc, char* argv[])
{
    GPU_Target* screen = GPU_Init(640, 480, GPU_DEFAULT_INIT_FLAGS);

    bool quit{false};
    SDL_Event e;

    GPU_Image* innerImage = GPU_LoadImage("inner.png");
    GPU_SetAnchor(innerImage, 0.0f, 0.0f);

    GPU_Image* offscreen = GPU_CreateImage(300, 300, GPU_FORMAT_RGBA);
    GPU_SetAnchor(offscreen, 0.0f, 0.0f);
    GPU_GetTarget(offscreen);

    while (!quit) {
        while (SDL_PollEvent(&e) != 0)  {
            if (e.type == SDL_QUIT) quit = true;
        }

        GPU_Clear(screen);

        GPU_Blit(innerImage, nullptr, offscreen->target, 0.0f, 0.0f);

        GPU_Blit(offscreen, nullptr, screen, 180, 50);

        GPU_Flip(screen);

    }

    GPU_FreeImage(offscreen);
    GPU_FreeImage(innerImage);

    GPU_Quit();

    return 0;
}
```
Bye!
