### ISSUE TITLE
GPU_CopyImage creates a target and delays freeing it, which causes problems

### ISSUE THREAD

**Issue by Wizzard033** [grimfang4/sdl-gpu#173]
I had to spend a couple hours today debugging my application because nothing was drawing from my own OpenGL code suddenly. It appears that GPU_CopyImage creates an OpenGL target that is only free'd when the image is free'd. This is implicit, and it messes up my rendering code. I can't use my OpenGL rendering code if the most recently used target isn't the screen and hasn't been free'd. So, I have to call `GPU_FreeTarget(image.target)` after my call to GPU_CopyImage to fix my problem. The worst part is I think it might be related to #171 because the problem does not always happen; I can sometimes use GPU_CopyImage without freeing the target.

**Comment by grimfang4** [comment]
Yes, SDL_gpu uses a render target because it's faster than downloading and then uploading the pixel data again.  Can you try using GPU_SetActiveTarget(screen) after GPU_CopyImage()?

**Comment by Wizzard033** [comment]
I keep running into this issue in different ways. I'm always able to fix it by calling FreeTarget to switch the OpenGL target back to the screen. However, I wish there was a way to make the context target the current target.

**Comment by Wizzard033** [comment]
I'm able to avoid this issue with gpu.SetActiveTarget being called in spots where SDL_gpu fails to set it to null.
