### ISSUE TITLE
How to blit image to imgui window?

### ISSUE THREAD

**Issue by cdyrssen** [grimfang4/sdl-gpu#175]
Environment:
SDL2
SDL-gpu
Dear ImGui

Goal:
I would like to render a custom texture within an ImGui window. My current approach to accomplishing this goes as follows:
1) Create an SDL_surface and edit the pixel data accordingly.
2) Generate a GPU_Image object using that SDL_surface.
3) Pass the resulting GPU_Image pointer to the ImGui::Image() function as the ImTextureID to render the image in the desired ImGui window.

Step three is where things fail. Instead of displaying the image specified, ImGui reverts to its default Font image. I haven't been able to figure out how to get Dear ImGui to trigger a GPU_Blit call for the given GPU_Image. Can anyone help me accomplish this?

**Comment by Wizzard033** [comment]
This is a pretty old issue, but take a look at this related issue
https://github.com/grimfang4/sdl-gpu/issues/120

You should use GPU_GetTextureHandle() and feed that handle directly to ImGui's Image function
This is my exact use case, but depending on your setup, this may not be the entire solution

**Comment by cdyrssen** [comment]
Ok I didn't see any mention of this method within the sdl-gpu documentation, but I will definitely give this a try and see how thing work out! Thanks.
