### ISSUE TITLE
Memory Leak in GPU_CreateRenderer_OpenGL_4

### ISSUE THREAD

**Issue by DiegoAce** [grimfang4/sdl-gpu#18]
I'm getting a memory leak from this function GPU_CreateRenderer_OpenGL_4.
It looks like renderer->impl is not freed in any of the GPU_FreeRenderer functions.

Adding:

if (renderer->impl)
        SDL_free(renderer->impl);

in GPU_CreateRenderer_OpenGL_4 solved the leak.

**Comment by grimfang4** [comment]
Yep!  This is an oversight from when I added the impl separation.  It is fixed in cc33fde4a5e30a39362cee273ee2fe64007ab366 now, for every renderer.  Thanks!
