### ISSUE TITLE
Won't compile current version on gcc/clang

### ISSUE THREAD

**Issue by neutonm** [grimfang4/sdl-gpu#182]
After cloning git, going through cmake and finally typing make I get the following errors. I have an old copy of sld-gpu, cloned year ago and it compiles without problems. GCC 6.3 and 9.1, clang 8

`Scanning dependencies of target SDL_gpu_shared
[  3%] Building C object src/CMakeFiles/SDL_gpu_shared.dir/externals/glew/glew.c.o

[  6%] Building C object src/CMakeFiles/SDL_gpu_shared.dir/SDL_gpu.c.o
/home/nm/git/sdl-gpu/src/SDL_gpu.c: In function ‘GPU_GetActiveTarget’:
/home/nm/git/sdl-gpu/src/SDL_gpu.c:537:35: error: ‘GPU_Context’ {aka ‘struct GPU_Context’} has no member named ‘active_target’
  537 |     return context_target->context->active_target;
      |                                   ^~
/home/nm/git/sdl-gpu/src/SDL_gpu.c: In function ‘GPU_SetActiveTarget’:
/home/nm/git/sdl-gpu/src/SDL_gpu.c:545:39: error: ‘struct GPU_RendererImpl’ has no member named ‘SetActiveTarget’
  545 |     return _gpu_current_renderer->impl->SetActiveTarget(_gpu_current_renderer, target);
      |                                       ^~
/home/nm/git/sdl-gpu/src/SDL_gpu.c: In function ‘GPU_GetDefaultCamera’:
/home/nm/git/sdl-gpu/src/SDL_gpu.c:916:68: warning: excess elements in struct initializer
  916 |     GPU_Camera cam = {0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, -100.0f, 100.0f, true};
      |                                                                    ^~~~~~
/home/nm/git/sdl-gpu/src/SDL_gpu.c:916:68: note: (near initialization for ‘cam’)
/home/nm/git/sdl-gpu/src/SDL_gpu.c:916:76: warning: excess elements in struct initializer
  916 |     GPU_Camera cam = {0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, -100.0f, 100.0f, true};
      |                                                                            ^~~~
/home/nm/git/sdl-gpu/src/SDL_gpu.c:916:76: note: (near initialization for ‘cam’)
/home/nm/git/sdl-gpu/src/SDL_gpu.c: In function ‘GPU_GetActiveTarget’:
/home/nm/git/sdl-gpu/src/SDL_gpu.c:538:1: warning: control reaches end of non-void function [-Wreturn-type]
  538 | }
      | ^
/home/nm/git/sdl-gpu/src/SDL_gpu.c: In function ‘GPU_SetActiveTarget’:
/home/nm/git/sdl-gpu/src/SDL_gpu.c:546:1: warning: control reaches end of non-void function [-Wreturn-type]
  546 | }
      | ^
make[2]: *** [src/CMakeFiles/SDL_gpu_shared.dir/build.make:76: src/CMakeFiles/SDL_gpu_shared.dir/SDL_gpu.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:124: src/CMakeFiles/SDL_gpu_shared.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by grimfang4** [comment]
This looks like an error from a mismatched SDL_gpu.h header file.  Can you double-check that you have the latest copy of the entire project and clean your intermediate build files?  Here's the line contradicting the first error:
https://github.com/grimfang4/sdl-gpu/blob/e3d350b325a0e0d0b3007f69ede62313df46c6ef/include/SDL_gpu.h#L395

**Comment by neutonm** [comment]
Checked, it was the last version with the active_target present in sdl_gpu.h but i ran git clone with depth=1 argument to make sure and got same result.

However, removing SDL_gpu* files from /usr/include/ actually solved the problem. Thanks, grimfang4!
