### ISSUE TITLE
Issues compiling on Raspberry Pi 4 with Broadcom VC6

### ISSUE THREAD

**Issue by NODESPLIT** [grimfang4/sdl-gpu#184]
I'm having some issues with compilation on the new Raspberry Pi 4 (released mid 2019, so understandable) I may just be missing something in cmake that could fix this and this issue is already known, so apologies in advance.

Here's the output of cmake -G "Unix Makefiles":

> CMake Warning:
>   No source or binary directory provided.  Both will be assumed to be the
>   same as the current working directory, but note that this warning will
>   become a fatal error in future CMake releases.
> 
> 
> CMake Warning at CMakeLists.txt:132 (message):
>   SDL2MAIN_LIBRARY is NOTFOUND
> 
> 
> -- Checking for module 'libstbi'
> --   No package 'libstbi' found
>  Using bundled version of stb-image
> -- Checking for module 'libstbi_write'
> --   No package 'libstbi_write' found
>  Using bundled version of stb-image-write
> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/pi/Build/sdl-gpu

Here's where make crashes:

> [ 30%] Building C object src/CMakeFiles/SDL_gpu.dir/renderer_OpenGL_4.c.o
> [ 33%] Building C object src/CMakeFiles/SDL_gpu.dir/renderer_GLES_1.c.o
> In file included from /home/pi/Build/sdl-gpu/src/renderer_GLES_1.c:24:
> /home/pi/Build/sdl-gpu/src/renderer_GL_common.inl: In function ‘init_features’:
> /home/pi/Build/sdl-gpu/src/renderer_GL_common.inl:494:33: error: ‘glBindFramebufferOES’ undeclared (first use in this function); did you mean ‘glBindFramebufferNOOP’?
>          glBindFramebufferPROC = glBindFramebufferOES;
>                                  ^~~~~~~~~~~~~~~~~~~~
>                                  glBindFramebufferNOOP
> /home/pi/Build/sdl-gpu/src/renderer_GL_common.inl:494:33: note: each undeclared identifier is reported only once for each function it appears in
> /home/pi/Build/sdl-gpu/src/renderer_GL_common.inl:495:40: error: ‘glCheckFramebufferStatusOES’ undeclared (first use in this function); did you mean ‘glCheckFramebufferStatusNOOP’?
>          glCheckFramebufferStatusPROC = glCheckFramebufferStatusOES;
>                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                         glCheckFramebufferStatusNOOP
> /home/pi/Build/sdl-gpu/src/renderer_GL_common.inl:496:36: error: ‘glDeleteFramebuffersOES’ undeclared (first use in this function); did you mean ‘glDeleteFramebuffersNOOP’?
>          glDeleteFramebuffersPROC = glDeleteFramebuffersOES;
>                                     ^~~~~~~~~~~~~~~~~~~~~~~
>                                     glDeleteFramebuffersNOOP
> /home/pi/Build/sdl-gpu/src/renderer_GL_common.inl:497:38: error: ‘glFramebufferTexture2DOES’ undeclared (first use in this function); did you mean ‘glFramebufferTexture2DNOOP’?
>          glFramebufferTexture2DPROC = glFramebufferTexture2DOES;
>                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
>                                       glFramebufferTexture2DNOOP
> /home/pi/Build/sdl-gpu/src/renderer_GL_common.inl:498:33: error: ‘glGenFramebuffersOES’ undeclared (first use in this function); did you mean ‘glGenFramebuffersNOOP’?
>          glGenFramebuffersPROC = glGenFramebuffersOES;
>                                  ^~~~~~~~~~~~~~~~~~~~
>                                  glGenFramebuffersNOOP
> /home/pi/Build/sdl-gpu/src/renderer_GL_common.inl:499:32: error: ‘glGenerateMipmapOES’ undeclared (first use in this function); did you mean ‘glGenerateMipmapNOOP’?
>          glGenerateMipmapPROC = glGenerateMipmapOES;
>                                 ^~~~~~~~~~~~~~~~~~~
>                                 glGenerateMipmapNOOP

It seems like the issue is related to what's being talked about in CMakeLists.txt near where it adds: `DSDL_GPU_USE_BROADCOM_RASPBERRYPI_WORKAROUND`.

Hope you can help, and thanks for all your work on this fantastic library!

**Comment by grimfang4** [comment]
I think you're right and this may be the same issue.  I don't have the hardware to test changes for that platform right now, but I may be able to borrow some soon.

I would first try defining SDL_GPU_DISABLE_GLES_1 and see if everything works fine for GLES 2.

To fix this more permanently, I would try moving SDL_gpu_GLES_1.h:19-28 into the #else block directly below it and then see if anything needs to be added for that SDL_GPU_USE_BROADCOM_RASPBERRYPI_WORKAROUND define to do the right thing.

**Comment by NODESPLIT** [comment]
Fantastic, I set the SDL_GPU_DISABLE_GLES_1 option on line 70 of CMakeLists.txt to ON and that fixed it. Thanks for pointing me in the right direction!

Also check out my [dev environment](https://imgur.com/a/alzkogQ), lol.

Now to make the rest of my build work...

**Comment by grimfang4** [comment]
I made some recent changes that make handling this a bit smoother.  The option is now just DISABLE_GLES_1 and this would be a good way to resolve this issue.
