### ISSUE TITLE
Empty black screen for GPU_UpdateImageBytes

### ISSUE THREAD

**Issue by sefeng211** [grimfang4/sdl-gpu#186]
Hi! 
I am trying to make this test file works https://github.com/grimfang4/sdl-gpu/blob/48fbeaad0d676ee9a5ebb604c1d11a6173742d8f/tests/image-formats/main.c. I am able to get those `bmp` image examples rendering on the screen, but for things like `image_bgr`, all I see is a black screen. 

There are no obvious errors. I am running Linux.

**Comment by sefeng211** [comment]
I am also seeing `GPU_GetTarget: DATA ERROR - Framebuffer incomplete with status: 0x8cd6.  Format 0x80e1 for framebuffers might not be supported on this hardware.`, could it be related to this ?

**Comment by grimfang4** [comment]
Yeah, that would mean that the BGR extension is not supported by your graphics driver.
