### ISSUE TITLE
Incorrect viewport size when using SDL_WINDOW_ALLOW_HIGHDPI

### ISSUE THREAD

**Issue by albertvaka** [grimfang4/sdl-gpu#188]
I use the following code to achieve scaling (virtual resolution) but maintaining aspect ratio (by letterboxing using a viewport). This is my Window resize event:

```
case SDL_WINDOWEVENT:
    if (event.window.event == SDL_WINDOWEVENT_SIZE_CHANGED) {
        const int width = event.window.data1;
        const int height = event.window.data2;

        GPU_SetWindowResolution(width, height);

        const float aspect = GAME_WIDTH/float(GAME_HEIGHT);

        const float scaleW = width/float(GAME_WIDTH);
        const float scaleH = height/float(GAME_HEIGHT);

        GPU_Rect rect;
        if (scaleW < scaleH) {
            rect.w = width;
            rect.h = width/aspect;
            rect.x = 0;
            rect.y = (height - rect.h)/2;
        } else {
            rect.w = height*aspect;
            rect.h = height;
            rect.x = (width - rect.w)/2;
            rect.y = 0;
        }

        GPU_SetViewport(target, rect);
        GPU_SetVirtualResolution(target,GAME_WIDTH, GAME_HEIGHT);
    }
```

This gets me this nice letterboxing effect:

<img width="1653" alt="Screen Shot 2020-05-04 at 20 20 30" src="https://user-images.githubusercontent.com/980842/80999342-cad37f00-8e44-11ea-9d8e-cfb88a23c9c3.png">
<img width="1434" alt="Screen Shot 2020-05-04 at 20 20 22" src="https://user-images.githubusercontent.com/980842/80999351-ceff9c80-8e44-11ea-888a-68edbe2a8f8f.png">

However, if I create my window with the flag `SDL_WINDOW_ALLOW_HIGHDPI` I get this result:

<img width="1170" alt="Screen Shot 2020-05-04 at 20 21 53" src="https://user-images.githubusercontent.com/980842/80999421-f6566980-8e44-11ea-9778-c51a0899ba0d.png">

**Comment by albertvaka** [comment]
This does not happen on Windows, only on Mac, though.

**Comment by grimfang4** [comment]
I might want to expose another function to make this cleaner to deal with.  SDL is not reporting the retina drawable size in that event.  Can you try this instead of getting data1 and data2?
`SDL_GL_GetDrawableSize(SDL_GetWindowFromID(event.window.windowID), &width, &height);`

**Comment by albertvaka** [comment]
Thanks a lot! That fixes the viewport calculation. However, the size I have to pass to `GPU_SetWindowResolution` is still the one incorrectly reported in the event data params, so it's all a bit confusing.

So, the final code looks like this:
```
if (event.window.event == SDL_WINDOWEVENT_SIZE_CHANGED) {
    GPU_SetWindowResolution(event.window.data1, event.window.data2);
    int width;
    int height;
    SDL_GL_GetDrawableSize(SDL_GetWindowFromID(event.window.windowID), &width, &height);
    [...]
```

**Comment by albertvaka** [comment]
Feel free to use any of my code above if you want to wrap this letterboxed-scale functionality and expose it in the API :)
