### ISSUE TITLE
[Question] build with emscripten

### ISSUE THREAD

**Issue by MateusDornelles** [grimfang4/sdl-gpu#190]
Hi, does sdl_gpu build with emscripten out of the box, or do i need to modify the build system ? I ask because when i tried to build it with emcmake it complained about not being able to find sdl2.

**Comment by albertvaka** [comment]
It builds out of the box, make sure you are passing the right compiler flags (eg: `-s USE_SDL=2`).

**Comment by grimfang4** [comment]
Is this a flag that should be added to the CMake script?

**Comment by albertvaka** [comment]
It's a bit more complicated than that, I've opened a PR with the needed changes to build on emscripten:

https://github.com/grimfang4/sdl-gpu/pull/205

With this, the following build commands succeed:

```
mkdir build
cd build
emcmake cmake ..
emmake make
```

This should allow you to use sdl-gpu as a static library from your emscripten project. I haven't tested this last part, though. When I build sdl-gpu games on emscripten I copy the entire sdl-gpu project into my project and I build everything statically using the same compiler flags for all the code (sdl-gpu + my project code together). But I assume it should work as a static library as well :)
