### ISSUE TITLE
Segmentation fault when accessing the windowID (Ubuntu)

### ISSUE THREAD

**Issue by NicolasPerdu** [grimfang4/sdl-gpu#20]
I have a segmentation fault on Ubuntu 16.04 at this line (it's working on windows 7) : 
`SDL_Window *win = SDL_GetWindowFromID(window->context->windowID);`

Here is the code for the test :
```
#include <iostream>
#include "gl_core_3_2.h"

#include "SDL.h"
#include "SDL_gpu.h"

int main() {
	GPU_Target* window = GPU_InitRenderer(GPU_RENDERER_OPENGL_3, 800, 600, GPU_DEFAULT_INIT_FLAGS);

	if (window == NULL) {
		GPU_LogError("Initialization Error: Could not create a OpenGL 3.2 renderer.\n");
		return 0;
	}

	SDL_Window *win = SDL_GetWindowFromID(window->context->windowID);
	return 0;
}
```

**Comment by grimfang4** [comment]
I'll take a look at this tomorrow!

**Comment by grimfang4** [comment]
I wasn't able to reproduce this yet.  Can you send me your gl_core_3_2.h and gl_core_3_2.c?  Does this sample work for you if you don't include the gl_core_3_2 header?

**Comment by NicolasPerdu** [comment]
Same error without gl_core_3_2.h  and  gl_core_3_2.c (generated with glLoadGen).

[gl_core_3_2.tar.gz](https://github.com/grimfang4/sdl-gpu/files/372488/gl_core_3_2.tar.gz)

**Comment by NicolasPerdu** [comment]
Problem solved! The error was caused by including another SDL.h file not compatible with the package libsdl2-dev.

**Comment by grimfang4** [comment]
Oh, excellent!
