### ISSUE TITLE
GPU_Init - transparent window background?

### ISSUE THREAD

**Issue by meuchel** [grimfang4/sdl-gpu#203]
Is there a way to have a transparent main opengl window background that one can see what is behind the window?
I checked the flags for GPU_Init but didn't found something regarding this.

I'm using Ubuntu 20.04 and have a project which currently already creates a native transparent xlib/xwindow opengl enabled and use SDL_CreateWindowFrom to be able to use SDL2 with it but now I want to integrate sdl-gpu.
So I see two possibilities:

1. Passing gl context of this xwindow to sdl-gpu which should be used by this library. 
2. Let do transparent background via GPU_Init / sdl-gpu without xwindow (should be preferred).

I would like to use option two because currently I have to manage events in XPending/XNextEvent but I would prefer to use SDLs SDL_PollEvent
How can I manage this with sdl-gpu?

**Comment by grimfang4** [comment]
I haven't tried this and I'm away from my Linux machine.  Does SDL_SetWindowOpacity() do what you need?  If you have an SDL_Window already, you can give that to SDL_gpu with GPU_SetInitWindow(myWindow).

**Comment by meuchel** [comment]
I tried SDL_SetWindowOpacity()  but it makes all transparent including the rendered items and not just the background.
Even the whole window with titlebar is no more visible with alpha=0.0

GPU_SetInitWindow would be an option, thx. I will try it later.

**Comment by meuchel** [comment]
GPU_SetInitWindow works with my transparent x11 window (after I made it with SDL_CreateWindowFrom to a SDL_window)

Unfortunately now events must be handled by XPending/XNextEvent
Even this does not work:
SDL_QuitSubSystem(SDL_INIT_EVENTS);
SDL_InitSubSystem(SDL_INIT_EVENTS);

Only using SDL_INIT_VIDEO restores SDL input handling but also creates a new window again with a background color.
I checked SDL sources but found no easy way to let handle the x11 events by SDL.

If someone has an idea let me know.
Because I can now use a transparent window I will close the issue.

**Comment by grimfang4** [comment]
You might check out SDL's shaped window functions.  They're not well-documented because they're not implemented across all pertinent platforms, but it looks like X11 is implemented.  You can find it in SDL_shape.h.

**Comment by meuchel** [comment]
The SDL shape is a good hint but is not the right thing. I can not draw outside of the shape and I want not to reshape again every frame. Also I need sometimes a title bar. 
I will try to hook somehow SDL, it should be possible to use SDL events with my custom xlib window.

**Comment by meuchel** [comment]
The SDL shape is a good hint but is not the right thing. I can not draw outside of the shape and I want not to reshape again every frame. Also I need sometimes a title bar. 
I will try to hook somehow SDL, it should be possible to use SDL events with my custom xlib window.

**Comment by meuchel** [comment]
I found a solution without changing SDL lib and posted it here, works with normal SDL and as well with sdl-gpu:

https://gist.github.com/meuchel/ad06b8951d6b99e840297d985a3b6b48

**Comment by grimfang4** [comment]
This is great!  Thanks for sharing.  Would you mind if I mention it on the SDL development mailing list for anyone else who is looking for such a feature?

**Comment by meuchel** [comment]
yes sure. I would be happy if you do so.
After all, it took me 4 years to get it up and running since my initial post https://forums.libsdl.org/viewtopic.php?p=44939 :)
The window even works with ImGui using imgui_impl_opengl3.h
