### ISSUE TITLE
Does not compile in Visual Studio after July 6th commit

### ISSUE THREAD

**Issue by DiegoAce** [grimfang4/sdl-gpu#21]
The commit on May 14th, 7c3d8fa612465a452fe9baf4463db0fb422746c7, works.
The first commit on July 6th, 48379773f891ba21c8e474a899e2496e9cc41387, does not compile, along with none of the following commits.

I am experiencing this using Visual Studio 14 on a Windows 10 64-bit machine, building for Debug or Release for Win32.
I follow the same procedure for building the two different versions.
I configure with cmake. Set SDL2 lib, SDL2main lib, and SDL2 include locations. Configure again. Generate. Open SDL_gpu.sln. Build SDL_gpu project.
It then succeeds for the May commit but fails for the July commit.
The errors mostly consist of undefined identifiers for all of the GL_ GPU_ and SDL_ identifiers.
Please let me know if I can be of more help.

**Comment by grimfang4** [comment]
Eric Wing noticed this too and provided a fix for errors on VS that are just warnings on GCC: 9e9bdbada3b233aff955e304fa3b91750211dc77
Does this solve your issue?

**Comment by DiegoAce** [comment]
That did it! 9e9bdbada3b233aff955e304fa3b91750211dc77 compiles fine. Thanks!

**Comment by grimfang4** [comment]
Cool, thanks for reporting on it. :)
