### ISSUE TITLE
Compute shaders

### ISSUE THREAD

**Issue by aganm** [grimfang4/sdl-gpu#210]
Would it be a lot of work to add compute shaders support to SDL gpu?

**Comment by grimfang4** [comment]
I've used compute shaders with Unity, but I don't have the experience yet on other platforms, so I don't grasp their system commonalities yet.  I would not be comfortable adding support for compute myself at this point, but I'd accept pull requests.

**Comment by grimfang4** [comment]
That said, you can force SDL_gpu to use a specific version of OpenGL and you can make your own direct GL API calls to work with compute shaders alongside SDL_gpu.
