### ISSUE TITLE
Issues about shapes and texture.

### ISSUE THREAD

**Issue by DaMoXin** [grimfang4/sdl-gpu#212]
https://www.sfml-dev.org/tutorials/2.5/graphics-shape.php    Can SDL achieve the effect of the third picture in the URL link,shapes can be textured.It still uses the rect function to display, but the image displayed is circular or other shape.

**Comment by grimfang4** [comment]
I'm a bit busy to put together an example, but yes, mapping a rectangular texture to a circle primitive is possible.  I don't think there's a really simple way to do it via the SDL_gpu API (you may have to calculate the texture coords yourself), but it can be done quickly with a shader.

**Comment by DaMoXin** [comment]
#include <SDL2/SDL.h>

#include <SDL2/SDL_image.h>

int main(int argc,char**argv)

{

SDL_Init(SDL_INIT_VIDEO);

SDL_Window*window=SDL_CreateWindow(“window1”, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 720, 1280, SDL_WINDOW_SHOWN);

SDL_Renderer*renderer=SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);

SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
SDL_RenderClear(renderer);

SDL_Surface*surface=IMG_Load("/Pictures/1.jpg");

SDL_Rect box={0, 0, 500, 500};

SDL_Texture*texture=SDL_CreateTextureFromSurface(renderer, surface);

SDL_RenderCopy(renderer, texture, NULL, &box);
int x,y;
for(x=0;x<=500;x++){
for(y=0;y<=500;y++){
if(((x-250)(x-250)+(y-250)(y-250))>250*250){
SDL_RenderDrawPoint(renderer,x,y);	}	}	}

SDL_RenderPresent(renderer);

SDL_Delay(12000);

SDL_FreeSurface(surface);

SDL_DestroyTexture(texture);

SDL_DestroyRenderer(renderer);

SDL_DestroyWindow(window);

SDL_Quit();

}
  I use the above code to achieve a circular image display, still using the rect function. If you want to try, just change the image path (IMG_ Load(" ")).
  It uses the equations of the circle and some knowledge of geometry(x-a)²+(y-b)²=r².Draw the area outside the circle in the rectangle as the background color(The area where the rect(SDL_Rect rect) and polygons within the rect do not intersect).Through this method, I can also realize the ellipse display of the picture (x²/a²+y²/b²=c²(a>b>0)), but I have no way for the figure with more than three vertices、triangle(the rectangle should be simpler).And this method is not efficient.Can anyone solve these two problems
