### ISSUE TITLE
Draw textured polygon?

### ISSUE THREAD

**Issue by nikita-yfh** [grimfang4/sdl-gpu#214]
I need to draw a non-convex textured polygon, or a set of textured triangles. 
![image](https://user-images.githubusercontent.com/70135428/108827580-da3fd680-75d6-11eb-9f07-e4d521a1533f.png)
In this picture, I am achieving the result using SDL_GFX, but its capabilities have become lacking: I can't rotate the image. Can I do something similar with SDL_GPU, and with the ability to rotate the image?

**Comment by aganm** [comment]
You could rotate each vertex before rendering to get this effect.

I believe SDL_gpu can do that with GPU_Rotate.

**Comment by nikita-yfh** [comment]
I solved this by using GPU_PrimitiveBatch, passing the vertex coordinates and texture coordinates to it.

**Comment by aganm** [comment]
Did you solve the image rotation too?

**Comment by nikita-yfh** [comment]
Yes, I solved. I rotate vertices with point rotation function (xd = x*cos(a) - y*sin(a);     yd = y*cos(a) + x*sin(a)).
![image](https://user-images.githubusercontent.com/70135428/110197757-c6119a00-7e5e-11eb-9c7e-5fa57ef2263b.png)
