### ISSUE TITLE
Blending to use for SetDepthTest(1)?

### ISSUE THREAD

**Issue by ramirez7** [grimfang4/sdl-gpu#216]
I'm trying to use depth testing to allow me to use z coordinates to control sprite rendering order, [as described in this ticket by @kirilledelman](https://github.com/grimfang4/sdl-gpu/issues/101)

However, I'm finding that the transparency of my images is still blocking sprites render "below." I confirmed I was using `GPU_BLEND_NORMAL`, which I'd expect to do what I wanted. I also tried manually changing the blend function/equations but got the same behavior

```
GPU_SetShapeBlendFunction( GPU_FUNC_SRC_ALPHA, GPU_FUNC_ONE_MINUS_SRC_ALPHA, GPU_FUNC_SRC_ALPHA, GPU_FUNC_ONE );
GPU_SetShapeBlendEquation( GPU_EQ_ADD, GPU_EQ_ADD);
```

Any tips? I'm a little new to lower-level computer graphics, so it may just be I don't know how these things work normally.

**Comment by ramirez7** [comment]
Also I wanted to add a big thank you for this library! [I'm actually calling it using some Haskell bindings I've been working on](https://gitlab.com/macaroni.dev/sdl-gpu-hs), and I'm loving the library more than other 2D Haskell graphics libraries I've tried before :)

**Comment by grimfang4** [comment]
Hey, glad you're finding it useful!

Depth testing is a separate concept from blending, so they only interact in the fact of our expectations (is something visible or not).  If the depth test decides that a pixel is obscured, it won't render at all, regardless of the blend mode.

The usual way to make them work nicely together is to collect your fully opaque objects (usually 3D geometry, not sprites like in SDL_gpu) separately from your transparent geometry.  Render your opaque objects first, in any order.  Then render your transparent objects in back-to-front order (z-sorting) using a typical blend mode (GPU_BLEND_NORMAL_KEEP_ALPHA or GPU_BLEND_NORMAL_ADD_ALPHA are good options).

The problem then is that many, many sprites have some transparency (like the corners and edges), so depth testing is not as useful as it is for 3D.  The actual rendering order is determined by the order in which you call GPU_Blit().  The depth testing just tries to avoid overdraw, which ruins transparency effects.

**Comment by ramirez7** [comment]
Thanks for the explanation! In that case, I'll handle the z sorting on my side. Not that much work anyways!
