### ISSUE TITLE
GPU_Circle and GPU_CircleFilled for small radius

### ISSUE THREAD

**Issue by GiovanniCmpaner** [grimfang4/sdl-gpu#226]
When drawing small circles, the rendered shape is not a circle.
Radius 0.05f:
![image](https://user-images.githubusercontent.com/22120203/90962183-849e3c00-e484-11ea-8fd4-74f217b78655.png)
Blue square is the bounding box and the purple shape should be the circle.

Code:
```cpp
int main(int argc, char* args[])
{
    const int screenWidth{ 400 }; // Pixels
    const int screenHeight{ 400 }; // Pixels
    
    const float realWidth{ 0.5f }; // Meters
    const float realHeight{ 0.5f }; // Meters
    
    GPU_Target* target = GPU_InitRenderer(GPU_RENDERER_OPENGL_3, screenWidth, screenHeight, GPU_DEFAULT_INIT_FLAGS);

    GPU_Clear(target);

    GPU_MatrixMode(target, GPU_PROJECTION);
    GPU_LoadIdentity();
    GPU_Ortho(-realHeight, +realHeight, -realWidth, +realWidth, 0, 1);

    GPU_MatrixMode(target, GPU_MODEL);
    GPU_LoadIdentity();
    GPU_SetLineThickness(0.005f);
    GPU_Rectangle(target, -0.05f, -0.05f, +0.05f, +0.05f, SDL_Color{ 0,0,255,255 });
    GPU_CircleFilled(target, 0.0f, 0.0f, 0.05f, SDL_Color{ 255,0,255,255 });
   
    GPU_Flip(target);

    while (1){}
}
```

In those codes:
https://github.com/grimfang4/sdl-gpu/blob/6df9944ccb344b9b0725b344fdfb201958eec90c/src/renderer_shapes_GL_common.inl#L346-L350

https://github.com/grimfang4/sdl-gpu/blob/6df9944ccb344b9b0725b344fdfb201958eec90c/src/renderer_shapes_GL_common.inl#L309-L318

A check for a minimal number of segments could be added:
```cpp
float dt = (1.25f/sqrtf(radius));
int numSegments = (int)(2*PI/dt)+1;
if (numSegments < 16)
{
    numSegments = 16;
    dt = 2.0f * PI / numSegments;
}
```

Result, radius 0.05f:
![image](https://user-images.githubusercontent.com/22120203/90962168-60daf600-e484-11ea-8d5a-92277537ae60.png)

**Comment by grimfang4** [comment]
Thanks for the clear repro code.  Can you confirm that b21d5bed8d1bbbbc236060a04ce076950faac05c fixes this issue for you and doesn't cause any unintended effects?

**Comment by GiovanniCmpaner** [comment]
Testing some circles, it showed good results:
![image](https://user-images.githubusercontent.com/22120203/152689013-c2a1619f-3941-46c6-8bf1-97e7cf5b2bbd.png)
Radius used: 0.01 / 0.05 / 0.1 / 0.2
Didn't see any problems with the changed code, it should only affect shapes with radius < 2.22.
