### ISSUE TITLE
Differentiate naming of static and shared libraries

### ISSUE THREAD

**Issue by DiegoAce** [grimfang4/sdl-gpu#23]
I'm building my project for 'Release' in vs2015. I'm using the libs generated from building SDL_gpu_shared for 'Release.' Using the latest SDL_gpu commit, building my project for 'Release' gets a lot of unresolved external errors for OpenGL functions. I must link opengl32.lib for my project to build. This is not the case when using the May 14th commit 7c3d8fa612465a452fe9baf4463db0fb422746c7. I do not need to link opengl32.lib in my project for the older commit. 
I'm not sure if this is desired behavior, but I wanted to let you know of the change.

**Comment by dhiahassen** [comment]
im not sure if this would be helpful , but i faced similar problems that i have fixed by reordering the linker command

**Comment by grimfang4** [comment]
I'm not sure about this yet.  The only build system changes have been for separating stb-image and stb-image-write.  Are you certain that the May 14th commit is different?  Does a debug build change anything?

**Comment by DiegoAce** [comment]
I redownloaded and repeated the process for the latest commit and was not able to repeat the error. Sorry if I caused any problems. I'm not sure why the other copy I have still forces me to link opengl32.lib.

**Comment by grimfang4** [comment]
Maybe you built and linked to SDL_gpu (static) instead of SDL_gpu_shared?

**Comment by DiegoAce** [comment]
That was it! I did not know building the static replaced the shared lib. Thanks for letting me know!

**Comment by grimfang4** [comment]
Oh, that makes sense to me now.  I think the solution here would be to change the build settings so that the static and dynamic libraries have different names.  Here's some discussion: http://stackoverflow.com/questions/2140129/what-is-proper-naming-convention-for-msvc-dlls-static-libraries-and-import-libr

**Comment by grimfang4** [comment]
Linked from there are some solutions that will work, directly from CMake devs: https://cmake.org/Bug/view.php?id=10190

I'll pick one of those when I get to it.

**Comment by grimfang4** [comment]
I added _s to Windows static libraries.  There may be more to be done for other platforms.
e3d350b325a0e0d0b3007f69ede62313df46c6ef
