### ISSUE TITLE
How to render an Image as transparent?

### ISSUE THREAD

**Issue by avahe-kellenberger** [grimfang4/sdl-gpu#230]
I'm wanting to render an image as partially transparent but haven't found a way to do so (without shaders). How can this be done?

**Comment by grimfang4** [comment]
The easiest way to do this is with the GPU_SetRGBA() function.  For partially transparent regions, you can load an image format that supports transparency (like PNG), edit the pixel data's alpha values, or use a special blend mode (see GPU_SetBlendMode()).  And of course you can use custom shaders.

**Comment by avahe-kellenberger** [comment]
Thanks, I'll explore these options
