### ISSUE TITLE
When building with Emscripten: Undeclared Identifiers

### ISSUE THREAD

**Issue by tadashibashi** [grimfang4/sdl-gpu#232]
Hi, I'm taking a stab at building SDL_gpu with Emscripten, but am running into a series of undeclared identifiers.
In the common inlined header, I'm getting a bunch of:

In file included from sdl-gpu\src\renderer_GLES_1.c:24:
sdl-gpu/src/renderer_GL_common.inl:524:33: error: use of undeclared identifier 'glBindFramebufferOES'; did you mean 'glBindFramebufferNOOP'?
        glBindFramebufferPROC = glBindFramebufferOES;

I tried including <GLES2/gl2.h>, just to see what would happen, and while it would build SDL_gpu, during wasm-ld linking there would be a list of undefined symbols.
Any insight into this problem would be greatly appreciated.

**Comment by albertvaka** [comment]
You should disable GLES1 and OpenGL when using emscripten. Try adding the following build-time define flags `-DSDL_GPU_DISABLE_OPENGL -DSDL_GPU_DISABLE_GLES_1`.

That should solve it, but I would recommend you actually disable GLES2 as well and just go with GLES3, by setting these additional flags: `-DSDL_GPU_DISABLE_GLES_2 -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2`

**Comment by tadashibashi** [comment]
Thanks a lot for your answer.

In my CMake, I had targeted those definitions only to the executable, so they weren't being accessed by the SDL_gpu library.

Adding the following line before the call to "add_subdirectory(lib/SDL_gpu)" has solved the problem:
`add_compile_definitions(SDL_GPU_DISABLE_OPENGL SDL_GPU_DISABLE_GLES_2 SDL_GPU_DISABLE_GLES_1 MIN_WEBGL_VERSION=2 MAX_WEBGL_VERSION=2)`
