### ISSUE TITLE
SIGSEGV illegal storage access when trying to access window after init

### ISSUE THREAD

**Issue by BTOdell** [grimfang4/sdl-gpu#234]
We're using [Nim](https://nim-lang.org/) and the [`sdl2_nim`](https://github.com/Vladar4/sdl2_nim) binding library to access sdl2 and sdl2_gpu. `GPU_Init` is invoked to create the screen target and this successfully creates the underlying window and everything works fine.

However, by default the window has no title or icon. We tried to use the code below to access the underlying window so we could call SDL functions for setting the title and icon. This works on Linux but on Windows it generates a fatal SIGSEGV exception when it accesses `target.context`:

```nim
let target = init(uint16 gameWidth, uint16 gameHeight, uint32 windowFlags)
if target == nil:
  raise newException(Exception, "Failed to init SDL!")

if target.context != nil:
  let window = getWindowFromId(target.context.windowID)
  window.setWindowTitle(title)
  if iconFilename.len > 0:
    let iconSurface = loadSurface(iconFilename)
    window.setWindowIcon(iconSurface)
    freeSurface(iconSurface)
```

![image](https://user-images.githubusercontent.com/1644309/165915940-ee3ebaa1-1acd-41b5-85b3-21644c4e7a5d.png)

My guess is that the binding wrapper struct for the `Target` object may be out of date and missing certain fields that cause the `context` field to be misaligned. We're going to review the bindings to see if we can find anything missing, but if you can suggest any solutions that would be great! Thanks!

I'm working on this with @avahe-kellenberger AND THERE IS ONLY 32 HOURS LEFT IN THE GAME JAM HELP!

**Comment by BTOdell** [comment]
It was the bindings...

**Comment by grimfang4** [comment]
Glad it was just that.  I hope it wasn't too much of a hurdle for your jam.
