### ISSUE TITLE
crash on sdl2_gpu when loading images

### ISSUE THREAD

**Issue by dhiahassen** [grimfang4/sdl-gpu#24]
i was compiling my game engine , and i got a crash when loading an image , after trying and trying i became sure that something is wrong with the internal code of the library , ( sdl2_gpu mingw release )
it is working as expected on android but not on windows with your prebuilt release , so i tried with sdl_gpu version 1 , and it was working fine ! but i can't switch now , even your space-tutorial example crashs using that release , exactly when loading the image , but when compiled with sdl_gpu version 1 it doesn't  , i afraid i will have to download visual studio to use it's release and see if it is stable . can you plz tell me what is wrong , or can you plz offer a new realease

**Comment by grimfang4** [comment]
There are lots and lots of changes and bug fixes since the last release.  I can't provide a full release yet, but here's a build of a recent snapshot of SDL2_gpu for mingw32:
http://dinomage.com/open/SDL2_gpu-mingw32%209-30-16.zip

**Comment by dhiahassen** [comment]
it looks like being fixed , when can i find the last src for android ?

**Comment by grimfang4** [comment]
:) Yep!
