### ISSUE TITLE
How to blit use batches in sdl gpu !!

### ISSUE THREAD

**Issue by dhiahassen** [grimfang4/sdl-gpu#25]
How draw batch is implemented in sdl gpu and how to use it, documentation is missing for this topis , and how to draw textured primitives ?

**Comment by dhiahassen** [comment]
how to use blit batches in sdl gpu ?

**Comment by NicolasPerdu** [comment]
There is an example here with the functions **BlitBatch** and **BlitBatchSeparate** using **GPU_TriangleBatch** : 
https://github.com/grimfang4/sdl-gpu/blob/master/tests/blit-batch/main.c

**GPU_BlitBatch** and **GPU_BlitBatchSeparate** should work the same way.

**Comment by dhiahassen** [comment]
it is soo long and complecated , can you plz explain the work of batch in sdl gpu , i mean what does the function expect from the caller to work correctly , thanks alot

**Comment by grimfang4** [comment]
There is some description of GPU_TriangleBatch() in the SDL_gpu.h header:
https://github.com/grimfang4/sdl-gpu/blob/master/include/SDL_gpu.h#L1397

Before you use that function, I should point out that SDL_gpu does automatic batching.  GPU_TriangleBatch() is for cases where you need to control the batching or when you want to render arbitrary geometry.

Here's a simple usage of GPU_TriangleBatch() to draw a single triangle:

```
unsigned short indices[3] = {0, 1, 2};  // These are references to the vertex array's vertices, 3 for a triangle
float values[8 * 3];  // Each vertex will need x, y, s, t, r, g, b, a (8 floats per vertex)
values[0] = x1;  // Position
values[1] = y1;
values[2] = s1;  // Texture coordinates (normalized)
values[3] = t1;
values[4] = r1;  // Color (normalized)
values[5] = g1;
values[6] = b1;
values[7] = a1;
values[8] = x2;  // Position
values[9] = y2;
values[10] = s2;  // Texture coordinates (normalized)
values[11] = t2;
values[12] = r2;  // Color (normalized)
values[13] = g2;
values[14] = b2;
values[15] = a2;
values[16] = x3;  // Position
values[17] = y3;
values[18] = s3;  // Texture coordinates (normalized)
values[19] = t3;
values[20] = r3;  // Color (normalized)
values[21] = g3;
values[22] = b3;
values[23] = a3;

GPU_TriangleBatch(image, target, 3, values, num_indices, indices, GPU_BATCH_XY_ST_RGBA);
```

**Comment by grimfang4** [comment]
There are no built-in functions for textured primitives, so GPU_TriangleBatch() is the way to go.  You might find useful code to implement them in:
https://github.com/grimfang4/sdl-gpu/blob/master/src/renderer_shapes_GL_common.inl

Those shape functions use macros to fill the blit buffer found around here:
https://github.com/grimfang4/sdl-gpu/blob/master/src/renderer_GL_common.inl#L3784

**Comment by NicolasPerdu** [comment]
Here is a simple example of the function BlitBatch used in the test: 
```
int main(int argc, char* argv[]) {
	GPU_Target* screen;
	int i;

	screen = GPU_Init(800, 600, GPU_DEFAULT_INIT_FLAGS);

	GPU_Image* image;
	int maxSprites;
	int numSprites;
	int floats_per_sprite;
	float* sprite_values;
	int val_n;
	Uint8 done;
	SDL_Event event;

	image = GPU_LoadImage("data/small_test.png");

	maxSprites = 50000;
	numSprites = 101;

	floats_per_sprite = 2 + 4 + 4;
	sprite_values = (float*)malloc(sizeof(float)*maxSprites*floats_per_sprite);
	val_n = 0;

	for (i = 0; i < maxSprites; i++) {
		// position
		sprite_values[val_n++] = rand() % screen->w;
		sprite_values[val_n++] = rand() % screen->h;

		// rects
		sprite_values[val_n++] = 0;
		sprite_values[val_n++] = 0;
		sprite_values[val_n++] = image->w;
		sprite_values[val_n++] = image->h;

		// colors
		sprite_values[val_n++] = 255;
		sprite_values[val_n++] = 255;
		sprite_values[val_n++] = 255;
		sprite_values[val_n++] = 255;
	}

	done = 0;
	while (!done) {
		while (SDL_PollEvent(&event)) {
			if (event.type == SDL_QUIT)
				done = 1;

			GPU_Clear(screen);
			BlitBatch(image, screen, numSprites, sprite_values, 0);
			GPU_Flip(screen);
		}
	}

	free(sprite_values);
	GPU_FreeImage(image);
	GPU_Quit();

	return 0;
}
```

**Comment by dhiahassen** [comment]
actualy when i checked the example to told me about i found it simple and easy , thanks alot gays really <3

**Comment by dhiahassen** [comment]
you can close this
