### ISSUE TITLE
Opengl (   glDrawElements ) is not working as expected with sdl gpu

### ISSUE THREAD

**Issue by dhiahassen** [grimfang4/sdl-gpu#28]
im trying to use ;
```

glEnable(GL_POINT_SIZE);
unsigned int indices[] = { 0, 256, 1, 257 };
glDrawElements(GL_POINTS,2,GL_UNSIGNED_INT,indices);

```
But im getting blank screen , do i have to setup someting before doing this ?

**Comment by grimfang4** [comment]
Have you set up your vertex buffer object for rendering (glBindBuffer, glEnableVertexAttribArray, glVertexAttribPointer)?

**Comment by dhiahassen** [comment]
i found that on the 3d demo , now ill do it , if not working ill tell you
