### ISSUE TITLE
GPU_CopyImageFromTarget produces upside-down image

### ISSUE THREAD

**Issue by Abestanis** [grimfang4/sdl-gpu#29]
If you pass a GPU_Target to GPU_CopyImageFromTarget that is created with GPU_LoadTarget, the resulting GPU_Image will be an upside-down version of the original GPU_Image passed to GPU_LoadTarget.

I believe this is caused because GPU_CopyImageFromTarget  calls CopySurfaceFromTarget which calls getRawTargetData which flips the data vertically.

Could GPU_CopyImageFromTarget  detect that the GPU_Target was created from an GPU_Image and just return a copy of that GPU_Image instead?

This code shows the glitch:

```
GPU_Target* screen = GPU_Init(400, 200, SDL_VIDEO_OPENGL);

GPU_Image* image = GPU_CreateImage(200, 200, GPU_FORMAT_RGBA);
GPU_Target* imageTarget = GPU_LoadTarget(image);
GPU_TriFilled(imageTarget, 0, 0, 200, 0, 100, 200, GPU_MakeColor(0, 0, 255, 255));
GPU_Image* targetCopy = GPU_CopyImageFromTarget(imageTarget);

GPU_Blit(image, NULL, screen, 100, 100);
GPU_Blit(targetCopy, NULL, screen, 300, 100);

GPU_Flip(screen);
```

**Comment by grimfang4** [comment]
I think this is a good point.  Can you check out 18f04250f00c7c389460c7478851cea6b358a868 to see if it works right for you?

**Comment by Abestanis** [comment]
Works perfectly!
Thank you!
