### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by zmeyc** [grimfang4/sdl-gpu#32]
I'm trying to build the library on Cygwin:

```
mkdir build-cygwin
cd build-cygwin
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$(PREFIX)" -DSDL_gpu_DEFAULT_BUILD_DEMOS=OFF ..
make
```

This fails with errors about CALLBACK macro not being defined. It's defined in bundled `GLEW/gl.h` only if both `_WIN32` and `__CYGWIN__` macros are present, so I added this switch to cmake commandline: 

```
 -DCMAKE_C_FLAGS="-D_WIN32"
```

The library now compiles, but linking step fails:

```
[  9%] Linking C shared library cygSDL2_gpu.dll
cd /cygdrive/c/Users/User/.../sdl-gpu/build-cygwin/src && /usr/bin/cmake.exe -E cmake_link_script CMakeFiles/SDL_gpu_shared.dir/link.txt --verbose=1
/usr/bin/cc  -D_WIN32   -shared -Wl,--enable-auto-import -o cygSDL2_gpu.dll -Wl,--out-implib,libSDL2_gpu.dll.a -Wl,--major-image-version,0,--minor-image-version,0 CMakeFiles/SDL_gpu_shared.dir/externals/glew/glew.c.o 
[skipped]
CMakeFiles/SDL_gpu_shared.dir/externals/stb_image_write/stb_image_write.c.o /cygdrive/c/Users/User/.../libroot/cygwin/lib/libSDL2.dll.a -Wl,-Bstatic -lm -Wl,-Bdynamic -lGL 
CMakeFiles/SDL_gpu_shared.dir/externals/glew/glew.c.o:glew.c:(.text+0x4ff): undefined reference to `__imp_wglGetProcAddress'
CMakeFiles/SDL_gpu_shared.dir/externals/glew/glew.c.o:glew.c:(.text+0x4ff): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_wglGetProcAddress'
CMakeFiles/SDL_gpu_shared.dir/externals/glew/glew.c.o:glew.c:(.text+0x537): undefined reference to `__imp_wglGetProcAddress'
CMakeFiles/SDL_gpu_shared.dir/externals/glew/glew.c.o:glew.c:(.text+0x537): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_wglGetProcAddress'
```

I've tried adding -lopengl32 to linker flags, but this didn't change anything. Any pointers are appreciated! I'm trying to link against native OpenGL, not the Cygwin's 
X11 OpenGL.

**Comment by grimfang4** [comment]
I'll put in a fix for that macro when I have a moment.  I did really think wgl was in OpenGL32, but maybe not?  Can you try linking gdi32 as well?

**Comment by mdparker** [comment]
The WGL stuff is definitely in OpenGL32. It's documented in MSDN and I've been loading it all in my OGL binding for D for years.

https://msdn.microsoft.com/en-us/library/windows/desktop/dd374386(v=vs.85).aspx

**Comment by zmeyc** [comment]
@grimfang4 @mdparker It turned out I had X11 OpenGL installed. On a clean Cygwin installation cmake failed on find_package(OpenGL), but after adding `-DCMAKE_LEGACY_CYGWIN_WIN32=1` it finally found the system OpenGL. Then I found the following related issue:

https://public.kitware.com/Bug/view.php?id=13050

So, it seems that X11 OpenGL is now the preferred one and system one will be used only if CMAKE_LEGACY_CYGWIN_WIN32 is set to 1. Imho, for games it makes more sense to use the system one, as it doesn't require X server to be bundled with the game.

Now the library links succesfully, demos still don't link - WinMain not found, investigating.

**Comment by zmeyc** [comment]
Seems to be SDL issue, it generates WinMain only when it detects MSVC. I disabled compilation of demos and the lib itself is working with my app.

**Comment by zmeyc** [comment]
Summarizing: build steps for Cygwin with native OpenGL are:

```
PREFIX = $(shell pwd)/libroot/cygwin

mkdir -p SDL/build-cygwin
(cd SDL/build-cygwin; ../configure --prefix="$(PREFIX)"; make; make install)

mkdir -p sdl-gpu/build-cygwin
(cd sdl-gpu/build-cygwin; cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$(PREFIX)" -DCMAKE_LEGACY_CYGWIN_WIN32=1 -DCMAKE_C_FLAGS="-D_WIN32" -DSDL_gpu_BUILD_DEMOS=OFF ..; make; make install)
```

Additionally, WinMain should be defined in the app.

**Comment by grimfang4** [comment]
Could you check with the latest commit that you no longer need to explicitly define _WIN32?

**Comment by zmeyc** [comment]
Latest master without -DCMAKE_C_FLAGS="-D_WIN32" :

```
...ThirdParty/sdl-gpu/src/externals/glew/GL/glxew.h:98:22: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
                      ^
```

**Comment by grimfang4** [comment]
Is X11 ever desired by Cygwin users?

**Comment by zmeyc** [comment]
Cygwin is switching to be X11-only, native OpenGL is deprecated mode... But shipping standalone games with separate X server is inconvenient. Probably it would make more sense to use MinGW or VS instead, but I'm using Swift lang which is currently stable only on Cygwin. I'm not sure if it's worth fixing this mode (Cygwin+native OpenGL) in sdl_gpu.

Here's my template project for using Swift with SDL, I'm in process of adding sdl_gpu (now works on OS X and Cygwin):
https://github.com/zmeyc/sdl-game-swift

**Comment by grimfang4** [comment]
Okay, I'll leave it the way it was for now, since I am not set up to test X11 on Cygwin.

Eric Wing has done some cool stuff with Swift.  You might want to compare notes: http://blurrrsdk.com/
