### ISSUE TITLE
VBOs unavailable when running over RDP

### ISSUE THREAD

**Issue by zmeyc** [grimfang4/sdl-gpu#33]
When running the app over RDP, sdl_gpu chooses OpenGL_1 renderer, but crashes on this line:
```
    #ifdef SDL_GPU_USE_BUFFER_PIPELINE
        // Create vertex array container and buffer

        glGenBuffers(2, cdata->blit_VBO); // SEGFAULT
```

glGenBuffers is NULL. Is there any fallbacks I can try enabling or are VBOs required?

**Comment by zmeyc** [comment]
```
GPU_InitRenderer(GPU_RENDERER_OPENGL_1_BASE,
```
works.

**Comment by grimfang4** [comment]
I haven't looked into RDP, but it appears that you don't get hardware accelerated graphics.  Microsoft only supplies a software rendering path for OpenGL 1.1, so that's why the OPENGL_BASE renderer works.  Be aware that several features are absent from that renderer.
