### ISSUE TITLE
CMake issues demos/tools/tests 

### ISSUE THREAD

**Issue by incompetentcoder** [grimfang4/sdl-gpu#34]
On my archlinux box the .so created is actually called SDL2_gpu - the Cmake wants to link demos/tools/tests to SDL_gpu though which obviously isn't found then. 
[ 16%] Linking C shared library libSDL2_gpu.so
[ 18%] Linking C executable 3d-demo
/usr/bin/ld: cannot find -lSDL_gpu

Additionally the path to the .so isn't added to the linker flags for the demos/tools/tests makefiles so the linker still can't find it unless you add -L${SDL_gpu_SOURCE_DIR}/src to the respective TEST_LIBS/DEMO_LIBS in their cmakelists.txt

**Comment by grimfang4** [comment]
This should be fixed in a57a7bb2674cf6c7a668cb91003ee1556a661eea.  Can you verify?

**Comment by bfloch** [comment]
Same issue on Linux (Fedora 25).

I suggest instead of specifying the linker paths and library directly supply the target name (sdl_gpu / sdl_gpu_shared) and CMake will figure out dependencies and paths for you.

**Comment by grimfang4** [comment]
Thanks!  That's what ended up happening in f68b0936214dd18659ddd473b4ad97940a387af3 when I ran into this issue again.
