### ISSUE TITLE
Problems with size in destiny sprites

### ISSUE THREAD

**Issue by damasko** [grimfang4/sdl-gpu#35]
Hello.
I'm trying to migrate my rendering system from SDL2 default rendering to SDL_Gpu, but I'm confusing about how this works.
In my previous rendering system, I was using two rectangles, one source rectangle to specify the portion of the texture and a destiny rectangle for display the position and the size (in pixels). The size of src and dst may vary. 

e.g: a source rect (x, y, w, h) with values of (0, 0, 256, 128) and a dst rect with values of (0, 0, 128, 64)

 Now i have 2 GPU_Rect src and dst, but due the openGL unit conversion this is not working, the sprites are too big for the screen size.
GPU_Ortho gives me strange results (and some images like the background needs to fill the screen).
I tried to use GPU_BlitScale too, but i don't know how to find stretch factor W and stretch factor H (i'm pretty new in opengl).
So i wondering if there is some funcion similar to SDL_RenderCopy that accepts a destiny rect to blit.

**Comment by grimfang4** [comment]
There is GPU_BlitRect(), which lets you specify a destination rect (GPU_Rect).

GPU_BlitScale() uses scaling factors that are multiplied into the image dimensions.  For example, a horizontal scaling factor of 2 would make the result twice as wide.  To get to a target width, you want to divide by the source width and multiply by the target width, e.g.:
GPU_BlitScale(image, NULL, screen, x, y, desired_w/image->w, desired_h/image->h);

**Comment by damasko** [comment]
This worked like a charm, many thanks!
