### ISSUE TITLE
Fixed Function Pipeline

### ISSUE THREAD

**Issue by mmontag** [grimfang4/sdl-gpu#38]
Is it possible to use the fixed-function pipeline with SDL_gpu? Any simple examples of this?

**Comment by mmontag** [comment]
P.S. I am developing on a Mac :)

> Platform Issue (MacOSX): When MacOSX 10.7 introduced support for OpenGL beyond 2.1, they also introduced the core/compatibility dichotomy. However, they did not introduce support for the compatibility profile itself. Instead, MacOSX gives you a choice: core profile for versions 3.2 or higher, or just version 2.1. There is no way to get access to features after 2.1 and still access the Fixed Function Pipeline.

https://www.opengl.org/wiki/Core_And_Compatibility_in_Contexts

**Comment by grimfang4** [comment]
There's no compatibility profile for GL 3.x in OS X, as your reference points out.  To use the fixed function pipeline, you must use GL 2.1.  SDL_gpu lets you easily request a GL 2 context that should do the right thing:
GPU_Target* screen = GPU_InitRenderer(GPU_RENDERER_OPENGL_2, 800, 600, GPU_DEFAULT_INIT_FLAGS);

You can also request a more specific OpenGL version like:
GPU_Target* screen = GPU_InitRendererByID(GPU_MakeRendererID("OpenGL 2.whatever", GPU_RENDERER_OPENGL_2, 2, 1), 800, 600, GPU_DEFAULT_INIT_FLAGS);

The GPU_RENDERER_OPENGL_2 tells SDL_gpu which code path to use.  The 2, 1 tells OpenGL which version to use when creating a new context.  If it fails, you get a NULL screen pointer.

**Comment by mmontag** [comment]
I have tried the suggestions but couldn't get the fixed pipeline to draw anything in my project. Only `glClear` had any effect. 

Closing the issue, but would be useful to see a small example to demonstrate legacy fixed function code.
