### ISSUE TITLE
GPU_BLEND_NORMAL problems with partial transparency

### ISSUE THREAD

**Issue by mutability** [grimfang4/sdl-gpu#41]
Not sure if this is a bug, a poor default, or intended behavior.

For reasons I don't entirely understand, blitting images with partial transparency and GPU_BLEND_NORMAL to a RGB target produces all-or-nothing transparency: the only pixels that make it to the target are those with an alpha of close 1.0, other pixels are just dropped. This is perhaps because the target doesn't have an alpha layer?

Calling `GPU_SetBlendFunction( image, GPU_FUNC_SRC_ALPHA, GPU_FUNC_ONE_MINUS_SRC_ALPHA, GPU_FUNC_ONE, GPU_FUNC_ZERO )` yields better behavior (partial transparency)

Should GPU_BLEND_NORMAL set something more like those values?
If not, it'd be handy to have another preset for the RGBA->RGB "normal" case.

**Comment by grimfang4** [comment]
The description would definitely be a bug.  Can you post some code to demonstrate the effect?  Then I can consider fixes.  Because GPU_BLEND_NORMAL is the default, I want it to behave the same on all platforms (i.e. it must be supported on all platforms).  Unfortunately, separate color and alpha blend functions are an OpenGL extension, so I can't assume support and have to use the most reasonable single blend function.

**Comment by mutability** [comment]
I'll try to get you a standalone testcase. The rough shape of it is pretty simple:

```
    // for historical reasons we write to an intermediate buffer, not direct to the framebuffer:
    GPU_SetInitWindow( SDL_GetWindowID( window ) );
    GPU_SetRequiredFeatures( GPU_FEATURE_RENDER_TARGETS );
    back_buffer = GPU_Init( WindowWidth, WindowHeight, window_flags );
    render_buffer = GPU_CreateImage( back_buffer->w, back_buffer->h, GPU_FORMAT_RGB );
    renderer = GPU_LoadTarget( render_buffer );
    // ...
    atlas = GPU_CreateImage( w, h, GPU_FORMAT_RGBA );
    GPU_SetBlending( atlas, GPU_TRUE );
    GPU_SetBlendMode( atlas, GPU_BLEND_NORMAL );
    GPU_SetImageFilter( atlas, GPU_FILTER_NEAREST );
    // call GPU_UpdateImage( atlas, ... ) to populate it, some pixels are semitransparent
    // ...
    GPU_BlitTransformX( atlas, &bounds, renderer, /* .. other args .. */ ); // called many times to layer sprites over each other
    // ...
    GPU_Blit( render_buffer, NULL, back_buffer, 0, 0 );
    GPU_Flip( back_buffer );
```

**Comment by mutability** [comment]
After trying and failing to build a testcase, it turns out this was actually a bug in the original code. When it needed to expand the atlas texture, it would blit from the existing texture to the new one without resetting the blending parameters, so with BLEND_NORMAL the alpha value would effectively get squared each time the atlas was expanded and only alphas close to 1.0 (or tiles loaded later) would survive.

Sorry for the false alarm!

**Comment by grimfang4** [comment]
Oh, excellent.  I had reviewed the blend function for this case and couldn't figure it out. :)
