### ISSUE TITLE
GPU_BlitRect doesn't align correctly

### ISSUE THREAD

**Issue by mutability** [grimfang4/sdl-gpu#46]
`GPU_BlitRect(image, NULL, target, NULL)` doesn't work as expected: the top-left corner of the image is not mapped to the top-left corner of the target. Instead you get a weird effect where the center of scaling is somewhere to the bottom-right.

Unscaled (image dimensions == target dimensions):

![screenshot from 2016-12-03 17-02-43](https://cloud.githubusercontent.com/assets/3055062/20860885/77ad1fea-b97a-11e6-8e3f-3bf0fbf4147e.png)

Scaling 1760x960 image to 886x522 target:

![screenshot from 2016-12-03 17-03-16](https://cloud.githubusercontent.com/assets/3055062/20860886/7dc7c59c-b97a-11e6-9700-8263a192736d.png)

Code in this case is simply:

```
        GPU_BlitRect( render_buffer, NULL, back_buffer, NULL );
```

(back_buffer is the framebuffer; render_buffer is a fixed-size GPU_Image that is the main render target; I call GPU_SetWindowResolution on back_buffer when WINDOWRESIZED is received)

**Comment by mutability** [comment]
I suspect this is because GPU_BlitRectX does:

```
    GPU_BlitTransformX(image, src_rect, target, dx + pivot_x, dy + pivot_y, pivot_x, pivot_y, degrees, scale_x, scale_y);
```

but that should be something like `dx + pivot_x * scale_x`

**Comment by grimfang4** [comment]
Thanks!
