### ISSUE TITLE
Basic Triangle Not Drawing

### ISSUE THREAD

**Issue by xgibbousx** [grimfang4/sdl-gpu#48]
Hi,

I am trying to render a simple triangle to the screen using the following tutorial code with sdl-gpu:

[Tutorial Source Code](https://open.gl/content/code/c2_triangle.txt)

My code base uses sdl-gpu and I have got the 3D spinning triangles to work.  However, I can't get the basic code above to work.

I am using the following paradigm:

1. Initialize GLEW.
2. Create Vertex Array Object.
3. Create a Vertex Buffer Object and copy the vertex data to it.
4. Bind Buffer and Buffer Data.
5. Create and compile the vertex shader.
6. Create and compile the fragment shader.
7. Link the vertex and fragment shader into a shader program.
8. Specify the layout of the vertex data with pointer.
9. Use glDrawArrays() in a while loop.

My main "while" loop uses "GPU_Clear(this->_renderer);" and "GPU_Flip(this->_renderer);" wrapping the glDrawArrays() listed above.

Is there something I am not doing with sdl-gpu to get the triangle above to render?

**Comment by kuhaut** [comment]
try this in your draw loop:
... sdl gpu draws
GPU_FlushBlitBuffer(); // raw GL begin
... glDrawArrays()
GPU_ResetRendererState(); // raw GL end
... sdl gpu drawing again

**Comment by xgibbousx** [comment]
I have tried wrapping "glDrawArrays()" in "GPU_FlushBlitBuffer();" and "GPU_ResetRendererState();" but it still doesn't render.

**Comment by kuhaut** [comment]
I meant all custom gl code of draw loop (select program, set texture, shader param etc.), not just the glDrawarrays. If that doesnt work i would guess to problem to be with opengl, not with sdl_gpu.

**Comment by xgibbousx** [comment]
You were right.  I was missing a bunch of things in the draw loop that I didn't know were necessary.

In the end I was able to initialize the mesh with:
1. glGenVertexArrays
2. glGenBuffers
3. glBindBuffer
4. glBufferData
5. glGetAttribLocation.

Then, in the draw loop I call:
1. GPU_FlushBlitBuffer
2. glBindVertexArray
3. glBindBuffer (again)
4. glUseProgram
5. glVertexAttribPointer
6. glEnableVertexAttribArray
7. glDrawArrays
8. GPU_ResetRendererState.

I didn't know that so many things are required to be called in the draw loop.  Most of the tutorial just put glDrawArrays in the draw loop.

Does the above look correct in terms of what needs to be in the draw loop?
