### ISSUE TITLE
GPU_GetContextTarget() always returns null

### ISSUE THREAD

**Issue by trs79** [grimfang4/sdl-gpu#49]
I'm using SDL 1.2.15 on Windows with the latest sdl_gpu and trying to run the init-demo sample. I get an exception when applyTargetCamera() is called because GPU_GetContextTarget() always returns null. I can't find any code that is actually initialising the context (I see some code that handles this if using SDL 2 on line 1368 of renderer_GL_common.inl, but I need to stay with SDL 1.2)

Does sdl_gpu still work with SDL 1.2?

**Comment by grimfang4** [comment]
This was a regression since I haven't done SDL 1.2 testing in a while.  Does it work for you after c8fb091bdd1ad52c3e6589763d856b4420b77dbe?

**Comment by trs79** [comment]
Thanks for the response, after your commit the init-demo sample is working fine
