### ISSUE TITLE
Run Shader on Blits from a GPU_Image Tileset

### ISSUE THREAD

**Issue by xgibbousx** [grimfang4/sdl-gpu#51]
Hi,

I have been successful in doing two things with sdl-gpu so far:

1. Use a GPU_Image tileset with GPU_BlitScale() to draw out 16x16 pixel tiles to create the level of my game.
2. Use GPU_LoadShader(), GPU_LinkShaders(), glGenVertexArrays(), glVertexAttribPointer(), etc. in order to create and modify shader triangles within my game.  I am able to pass in vertex data and utilize attributes, uniforms, position, color, etc. to modify the shaders during rendering.

One question is as follows:

1. What is a good method to apply/run a shader (from point 2 above) on a 16x16 blit (from point 1 above)?  In other words, how do I target only specific 16x16 blit tiles to be affected by a particular shader?

A second question is as follows:

2. What is a good method to have a shader apply across multiple 16x16 blits as a whole?  For example, where a light would diffuse across an area of 20x20 tiles, not just each tile individually.  Would each tile get its own shader class?  How would multiple tiles share 1 shader?

Thanks so much!

**Comment by xgibbousx** [comment]
I was able to make some progress on this.  I have been using the "tests/shader-attributes" source code as a reference.  I have found the following:

If I wrap a "GPU_Blit()" call with "GPU_ActivateShaderProgram(program, &block)" [to activate the shader] and "GPU_ActivateShaderProgram(GPU_GetContextTarget()->context->default_textured_shader_program, NULL)" [to deactivate the shader] then the activated shader will only affect the blits/tiles drawn between the activate/deactivate shader call.  This is exactly what I was trying to do.

It seems a little odd to have to wrap the draw calls with activate/deactivate shader but if it works then that's fine.  I will be thinking about another way to do this though.

Another note:

Since I am using GPU_Blit(), the shader seems to automatically pick up the tile vertices.  In other words, I don't need to create a mesh, vertex buffer object, vertex array object, bind, etc.  The other interesting thing is that the shader affects all of the tile blits as a whole instead of individually as they are blitted.  This actually answers my second question.

Therefore, all in all I think I got everything working for now.

**Comment by grimfang4** [comment]
Sorry I wasn't able to get back to you before you put more time into this.

It seems like you just needed a better demo of how to use shaders in a real application with SDL_gpu?  I think you've pretty much gotten there.


Load shader program:
```
Uint32 vert = GPU_LoadShader(GPU_VERTEX_SHADER, vert_filename);
Uint32 frag= GPU_LoadShader(GPU_FRAGMENT_SHADER, frag_filename);
Uint32 shader = GPU_LinkShaders(vert, frag);
```

Then load a shader block so that SDL_gpu can use the standard attributes for blitting with that shader:
`GPU_ShaderBlock block = GPU_LoadShaderBlock(shader, "gpu_Vertex", "gpu_TexCoord", "gpu_Color", "gpu_ModelViewProjectionMatrix");`

Also get the locations of custom uniforms/attributes you want to use:
`int hue_loc = GPU_GetUniformLocation(shader, "hue");`

Then when you want to use it, you activate it, set uniforms, blit, then deactivate (if necessary):
```
GPU_ActivateShaderProgram(shader, &block);
GPU_SetUniformf(hue_loc, 0.5f);
GPU_Blit(image, NULL, screen, x, y);
GPU_ActivateShaderProgram(0, NULL);  // Using 0 and NULL will reset it to the appropriate default shader
```

**Comment by grimfang4** [comment]
If you use C++, you're welcome to mess around with my Shader class that stores all that stuff in one place, caches uniform locations, and supports unversioned GLSL 300-compatible shaders.

I use it like so:

Load:
```
Shader shader;
shader.load(vert_filename, frag_filename);
// Do this if you write unversioned shaders that can work on OpenGL 3+ and GLES 2+
// shader.load_unversioned(vert_filename, frag_filename);
```

Use:
```
shader.activate();
GPU_SetUniformf(shader.get_location("hue"), 0.5f);  // Location is cached so doesn't need to be preloaded
GPU_Blit(image, NULL, screen, x, y);
shader.deactivate();
```


[Shader class.zip](https://github.com/grimfang4/sdl-gpu/files/638311/Shader.class.zip)

**Comment by xgibbousx** [comment]
Wow, your code above is spot on.  It's exactly what I meant.  I will try to use the code formatting from now on to make things more legible.

What I thought was interesting is that "gpu_Vertex",  "gpu_TexCoord",  "gpu_Color", "gpu_ModelViewProjectionMatrix" are all "standard attributes."  Is this why the shader automatically works with GPU_Blit() in terms of "vertex, texture, color, matrix"?

Thanks for the Shader class, it has all the concepts I was talking about written very well.  I will certainly utilize this.

**Comment by grimfang4** [comment]
Yes, GPU_Blit() uses the shader block to know which attributes to pass that data to.  That data is the typical for 2D rendering to a quad and this setup just organizes it in a way.

You might also find it useful to know that the first texture sampler will be image unit 0, which is what GPU_Blit() assumes and uses.  If your shader uses multiple texture samplers, then use GPU_SetShaderImage() to link each of them to a GPU_Image and a unique image unit.

**Comment by xgibbousx** [comment]
Ha, you are basically reading my mind.  I was literally just digging through "tests/multitexture" and found GPU_SetShaderImage() before I even saw your latest post.  It's exactly what I am trying to do right now.  I am trying to sample a diffuse and normal map texture in the fragment code.

I may have some other questions regarding this process and will let you know in a separate issue.

Thanks so much for all of your help!
