### ISSUE TITLE
SDL_GPU w/ SPARK Particle Engine

### ISSUE THREAD

**Issue by xgibbousx** [grimfang4/sdl-gpu#52]
Hi,

I am trying to get my SDL_GPU implementation working with the SPARK particle engine demo code as follows:

[Demo Code](https://github.com/Synxis/SPARK/blob/spark2/demos/src/SPKTest.cpp)

I am essentially using the following paradigm:

Initialization of OpenGL/SDL_GPU/SPARK:
- GPU_Init(); (from SDL_GPU)
- loadTexture(); (from SPARK demo code) -> This uses SDL_LoadBMP();, glGenTextures(), glBindTexture(), glTexImage2D(), etc.
- glClearColor(); (SPARK/OpenGL)
- glMatrixMode(); (SPARK/OpenGL)
- glLoadIdentity(); (SPARK/OpenGL)
- SPK::GL::GLQuadRenderer::create();
- SPK::SphericEmitter::create();
- etc.

Render Loop:
- GPU_Clear(); (SDL_GPU)
- glClear(); (SPARK/OpenGL)
- glMatrixMode(); (SPARK/OpenGL)
- glTranslatef(); (SPARK/OpenGL)
- glRotatef(); (SPARK/OpenGL)
- glBegin(); (SPARK/OpenGL)
- glVertex3f() x4 for quad (SPARK/OpenGL)
- drawBoundingBox(); for particle system (SPARK/OpenGL)
- renderParticles(); (Spark/OpenGL)
- glEnd(); (SPARK/OpenGL)
- GPU_Flip(); (SDL_GPU)

No matter what I try, I can never get anything (even a basic quad) to draw to the screen.  I have tried the following:

- Wrap render loop with GPU_FlushBlitBuffer(); and GPU_ResetRendererState();.
- Use GPU_MatrixMode(), GPU_PushMatrix(), GPU_LoadIdentity(), and GPU_PopMatrix() in the render loop.
- Use my own SDL_GL_SwapWindow() instead of GPU_Flip().
- Dozens of other small tests that didn't work.

I have even tried to simplify the paradigm where I am only trying to just render a basic quad doing the following:

Initialization of OpenGL/SDL_GPU:
- GPU_Init(); (from SDL_GPU)
- glClearColor(); (SPARK/OpenGL)
- glMatrixMode(); (SPARK/OpenGL)
- glLoadIdentity(); (SPARK/OpenGL)

Render Loop:
- GPU_Clear(); (SDL_GPU)
- glClear(); (SPARK/OpenGL)
- glMatrixMode(); (SPARK/OpenGL)
- glBegin(); (SPARK/OpenGL)
- glVertex3f() x4 for quad (SPARK/OpenGL)
- glEnd(); (SPARK/OpenGL)
- GPU_Flip(); (SDL_GPU)

The above paradigm should be one of the minimal ways to draw an OpenGL quad to the screen.  However, I am not able to get the quad to render to the screen at all.

My questions are as follows:

- Does SDL_GPU work with glBegin(), glEnd(), glVertex3f()?
- Does SDL_GPU work with SDL_LoadBMP(), glGenTextures(), glBindTexture(), glTexImage2D(), etc. or do I need to convert this texture to a GPU_Image?
- Should SDL_GPU be working with at least the basic paradigm above or is there an incompatibility that you can see?
- I am using a replacement for gluPerspective() as seen [here](http://stackoverflow.com/questions/12943164/replacement-for-gluperspective-with-glfrustrum).  Could this or an improper glTranslatef() or glRotatef() be causing nothing to be drawn to the screen?
- Based on what you can see with SPARK, is there any way to get SDL_GPU to work with SPARK or is there something I am missing that makes them incompatible?
- Do you have any ideas on why I can't get either of the paradigms above to draw anything to the screen?

I have successfully got SDL_GPU to work with everything so far (e.g. sprites, tilesets, shaders, etc.) and am very much looking forward to getting it working with a great particle engine such as SPARK.

Thanks so much for any help you can provide!

**Comment by grimfang4** [comment]
SPARK didn't build cleanly for me on OS X, so I can only give you some tips for now.

If you want to use glBegin/glEnd (fixed function pipeline calls), you need to be using a backward-compatible GL context.  For all desktop platforms, this would be OpenGL 2.1.  OS X, in particular, has no compatibility profile in GL 3+.  To make this happen in SDL_gpu, call GPU_InitRenderer() with GPU_RENDERER_OPENGL_2.

Once the context is created (you have a screen GPU_Target), then you're all set to make GL calls and ignore SDL_gpu.  Look at the [3d-demo](https://github.com/grimfang4/sdl-gpu/blob/master/demos/3d/main.c) in the SDL_gpu repository (this shows mixed SDL_gpu and OpenGL calls) or look up OpenGL/SDL2 tutorials for some demo code.

You can use SDL_LoadBMP().  If you want to create you own textures, you can do that with GL calls.  If you want SDL_gpu to create the texture, then either use GPU_LoadImage() or GPU_CopyImageFromSurface().  SDL_gpu also has GPU_CreateImageUsingTexture(), which is not really recommended if you can avoid it, but it's there just in case.

If you're not seeing anything, I'd suspect that the GL state isn't right.  Start from the [3d-demo](https://github.com/grimfang4/sdl-gpu/blob/master/demos/3d/main.c) and you should be able to work it out.

**Comment by xgibbousx** [comment]
Thanks so much for the quick response and all the great tips.

To your points:

- I've only been able to get SPARK to build on Visual Studio 2015.
- Very interesting about glBegin/glEnd.  I didn't realize they were deprecated and replaced by VBO.  I was only using them because they were in the tutorial.
- I will try out GPU_RENDERER_OPENGL_2.
- I will try out using an SDL_GPU texture.
- I will closely study the 3D demo to see if it helps.

One other question:

- SPARK needs an "index" or integer based unique ID to the texture.  I guess glGenTextures() and glBindTexture() sets this in the SPARK demo code.  Is there a way to access this "index" or unique ID through an SDL_Image?

Thanks and I will let you know how things progress.

**Comment by xgibbousx** [comment]
Also:

"If you're not seeing anything, I'd suspect that the GL state isn't right."

What are some ways to debug the GL state?

Thanks!

**Comment by grimfang4** [comment]
Yep, glBegin and friends aren't available in GL 4+ nor in the core profile for GL 3.2+ (GL 3.1 may have ARB_compatibility).  VBOs and now VAOs are necessary in modern OpenGL, meaning you upload chunks of data at once to minimize transfer overhead and state changes.

The texture handle can be accessed if you know which renderer you are using.  I could make this a bit cleaner in the future, but for now given a GPU_Image* image:
```
#include "SDL_gpu_OpenGL_2.h"
...
GLuint texture_handle = ((GPU_IMAGE_DATA*)image->data)->handle;
```

I do use a GL debugger, but I always forget which one works best for me.  Try gDEBugger or APItrace.
