### ISSUE TITLE
Access GPU_Image/Texture Handle

### ISSUE THREAD

**Issue by xgibbousx** [grimfang4/sdl-gpu#54]
I am trying to access the handle/ID of a texture through GPU_Image.  My code looks like the following:

`GPU_Image *textureImage = graphics.loadImage("content/particles/flare.bmp");`
`GLuint Texture = ((GPU_IMAGE_DATA*)textureImage->data)->handle;`

I get build errors stating that GPU_IMAGE_DATA is an undeclared identifier and that textureImage expects a ')'.  I am using Visual Studio 2015 with C++.

My questions are as follows:

- What is the best way to access the handle/ID of an image?
- What did I do wrong in my code?

Thanks so much for the help.

**Comment by grimfang4** [comment]
Did you include one of the SDL_gpu_OpenGL_*.h headers?  Those headers have the defines that let you reach into the opaque renderer-specific structures.

**Comment by xgibbousx** [comment]
Ah, works perfectly now!

Thanks so much!
