### ISSUE TITLE
Best way for a heavy shader use in SDL_Gpu?

### ISSUE THREAD

**Issue by damasko** [grimfang4/sdl-gpu#61]
I'm planning to do a game that uses multiple shaders. Currently i'm using GPU_Targets for this and works pretty well, but i feel that I'm using too many copies and blit calls (I'm copying from a GPU_Target to another with GPU_Blit) , and this may keep growing. Is this the proper way? I see people using OpenGL FBOs to do this kind of effects, but I don't know if SDL_gpu is using this under the hood.

Here is a example scene with a few shaders, it's made by using multiple copies and combining them:
![paisaje](https://cloud.githubusercontent.com/assets/1877469/23990930/d895e770-0a37-11e7-891d-bae8043c8367.png)

Any help would be appreciated.

**Comment by grimfang4** [comment]
Yep, FBOs (framebuffer objects) with attached texture are the main way OpenGL represents targetable buffers of pixels.  That's what SDL_gpu uses.

Depending on how your shader effects are achieved, you might be able to apply shaders to multiple blits on the same target.  Also, if you are doing 1:1 sampling and rendering in a shader (i.e. you only read from the texel you are writing to), you can blit a texture onto itself to save a copy.

**Comment by damasko** [comment]
Thanks for the fast reply. Nice to see that I'm using the correct way with SDL_gpu, I was worried about performance or strange behaviours. I'll try to follow your advices.
Very great library, thanks!
