### ISSUE TITLE
Segmentation fault when loading image using GPU_LoadImage

### ISSUE THREAD

**Issue by labuzm** [grimfang4/sdl-gpu#64]
While trying to load an image using the GPU_LoadImage function and passing in a name of an existing directory, segfault error occurs.

Example code:

    #include "SDL.h"
    #include "SDL_gpu.h"

    int main(int argc, char* argv[])
    {
	    GPU_Target* screen;
	    screen = GPU_Init(800, 600, GPU_DEFAULT_INIT_FLAGS);
        GPU_Image *image = GPU_LoadImage("directory");
	    GPU_Quit();
	    return 0;
    }

**Comment by grimfang4** [comment]
I haven't been able to repro this on Windows / MinGW32.  Loading relies on SDL_RWops and handles NULL result, so if there's a segfault there, then it's possible that SDL_RWFromFile() is giving non-NULL on directories.  Which platform and compiler are you using?  Which version of SDL?

**Comment by ephemer** [comment]
Apparently mac OS / Linux handle directories differently to Windows / FreeBSD, I read this randomly the other day, so it probably has something to do with it:

https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback

**Comment by labuzm** [comment]
I'm on Ubuntu / GCC 5.4 / SDL 2.0.5 and yes, exactly as you suspected, SDL_RWFromFile() is giving non-NULL on directories.

**Comment by labuzm** [comment]
fopen() (which is used under the hood on unix systems for opening files) returns a valid file descriptor for directories opened in "r" mode. One way to fix this is to set the mode to "r+", but I'm not sure if this won't break anything on other platforms.

**Comment by grimfang4** [comment]
I recommend reporting this on SDL's Bugzilla (https://bugzilla.libsdl.org).  I think it would be best handled there instead of as a special case in SDL_gpu.  In the meantime, if you really do need to handle directories and files interchangeably, you can use something like this in a wrapper of GPU_LoadImage():

```
#include <sys/stat.h>
bool is_dir(const char* filename)
{
    struct stat status;
    stat(filename, &status);

    return (status.st_mode & S_IFDIR);
}
```

**Comment by labuzm** [comment]
:+1:
