### ISSUE TITLE
SDL_gpu re-uploads textures every frame on Blit?

### ISSUE THREAD

**Issue by ephemer** [grimfang4/sdl-gpu#70]
I'm running into the issue where blitting 5-10 textures per frame on Android takes about 40ms, which obviously completely destroys my framerate.

Is it possible that SDL_gpu is re-uploading the textures every frame? Is it possible to leave the textures in GPU memory and just "re-draw/re-blit" them, either in the same or a different location?

**Comment by grimfang4** [comment]
I've left a response that might help a bit on #50.  It may be that the default VBO upload method is not a good idea on your device.  I would try SDL_GPU_USE_BUFFER_RESET, which maybe should be the default at some point.

**Comment by ephemer** [comment]
Thanks a lot for the tip, this makes a huge difference!

Both SDL_GPU_USE_BUFFER_MAPPING and SDL_GPU_USE_BUFFER_RESET are at least 5-10x faster on the various Android phones I have sitting around here. The slowest by far is still the Samsung Galaxy S7, probably because it has a huge screen resolution. It is sitting at a reported 80fps though now, which is fine (it does seem to have some spikes though). Compiling with either of those flags also makes a reasonable (positive) difference on the Nexus 5 and the Galaxy S5.

This result is potentially confounded by the fact that I compiled with GLESv3 as well, but you'd have a better idea than I do of whether that should have a large performance impact or not.

As is, I'd strongly recommend enabling SDL_GPU_USE_BUFFER_MAPPING (it seems the fastest) by default for Android builds. FYI, all of these devices are running Android 6.0 or 7.0.

**Comment by ephemer** [comment]
@grimfang4 I just saw your latest commit making this the default on Android. Awesome stuff, I just sent you a modest donation of my own cash as a thank you for the great support

**Comment by grimfang4** [comment]
Thanks so much!  Donations help me to spend extra time on SDL_gpu and it gets better for everyone. :D
