### ISSUE TITLE
iOS Does Not Compile Commit 940761f and Newer

### ISSUE THREAD

**Issue by DiegoAce** [grimfang4/sdl-gpu#74]
Commit 940761f and newer do not compile for iOS. Commit 3d6c98a does compile. I attached the error log. The full log is in the txt but I attached the png because it's a bit easier to read.

<img width="2235" alt="ioscrashlog" src="https://user-images.githubusercontent.com/19171919/28754432-9c27bc08-750a-11e7-9ebe-9a5dea6d4cf9.png">

[iosCrashLog.txt](https://github.com/grimfang4/sdl-gpu/files/1185745/iosCrashLog.txt)

**Comment by grimfang4** [comment]
This seems to be saying that GLAPIENTRY is not defined?  Can you try d6cc5db2a62ae656ad703189636825984b8bbf68 to see if that is resolved?

**Comment by DiegoAce** [comment]
Yep! d6cc5db compiles fine on iOS.

**Comment by grimfang4** [comment]
Great, thanks for the report!

**Comment by ephemer** [comment]
This can be closed now I guess?
