### ISSUE TITLE
Strange scaling issues with GPU_BlitRect

### ISSUE THREAD

**Issue by incinirate** [grimfang4/sdl-gpu#76]
Using `GPU_BlitRect` when the source image is at certain widths/heights setting `NULL` as the destination rect (which should cover the whole destination target) produces unexpected results..

Here is an example:
https://hastebin.com/watedimume.c

The output:
![Example](https://inci.ninja/imgs/ou6ayz.png)

As you can see, the yellow rectangle is offset to the right, when it should cover the whole window.

**Comment by incinirate** [comment]
This seems to happen only when the width/height of the image are odd and the offset is equal to half the amount the image is scaled in that dimension, eg. the image's dimensions are 5x6, the x coordinate of the blitted rect is offset by half the amount it is scaled by, and 7x9 both dimensions are offset (by half the amount that they are scaled)

**Comment by grimfang4** [comment]
It's possible that it's a scaled snapping issue.  Can you try disabling with `GPU_SetSnapMode(image, GPU_SNAP_NONE)`?

**Comment by incinirate** [comment]
Yep that fixes it, thanks!

**Comment by grimfang4** [comment]
Cool, I'll have to set aside some time to fix the snapping as per #37.  Thanks for the report!
