### ISSUE TITLE
Modulation color AND additive color

### ISSUE THREAD

**Issue by kirilledelman** [grimfang4/sdl-gpu#83]
Hi,

I was wondering if it's at all possible to have not only modulation color, as is set by `GPU_SetColor`, but also additive color, and use them together. I'm specifically interested in GLES2 implementation.

So the final RGB color would be:
`Source * Modulated + Additive`

Is it something that can be done by writing a shader (or is that not supported by ES2?), is it possible at all?

I wrote an exporter for simple Flash animations (I know, Flash) in JSON+pngs format for a [different project](http://gogoat.com/pixelbox/example9.html), and now I'm trying to write a class that would render these. Flash has additive and modulation together color transform - that's what this is for.

Thanks for a great library.

**Comment by grimfang4** [comment]
The clearest way would be a shader.  OpenGL ES 2.0 supports GLSL ES 1.00 (#version 100).  Look at the simple-shader demo for reference.  The shader at demos/data/shaders/color.frag is easily changed for this.

**Comment by grimfang4** [comment]
If you don't care about the destination values at all, you might be able to use a special blend mode to achieve this instead.

**Comment by kirilledelman** [comment]
Thank you, this helps. I'll take a look at the sample shader.
