### ISSUE TITLE
Raspberry Pi performance

### ISSUE THREAD

**Issue by kirilledelman** [grimfang4/sdl-gpu#84]
Hi,
I'm not sure if you'd be able to answer this question or not, but, do you know if running SDL_gpu projects on Raspberry Pi - is rendering hardware accelerated at all?

I found a serious bottleneck, that's kind of a show-stopper - unless I'm misunderstanding something here.

Rendering 68 `GPU_Blit` of a 43 × 29px image - I get 170 frames per second.

Rendering 68 `GPU_Blit` of a 256 × 256px image - I get 18 frames per second.

That's 10 times slower - doesn't even seem to make sense for an unaccelerated software renderer:
In a ( 256 x 256 ) image, there are 54 ( 43 x 29 ) sized images. The difference in fps should be smaller.

`GPU_GetCurrentRenderer` returns a renderer with name OpenGL version 2.0. It's hard to believe this is as fast as it can work in hardware.

Any clues?

EDIT:
I've set image filter to GPU_FILTER_NEAREST, turned off snapping, and started rendering to a target 1/4th the resolution and then blitting it stretched to screen for a significant improvement in framerate. The same demo runs at 30fps.

**Comment by grimfang4** [comment]
Are you running it under X11?  Those numbers make it sound like it may be using the software path in Mesa.  There's some discussion about this at the moment on the SDL Discourse.  I'll let you know if anything comes of that.

What kind of performance do you get out of glxgears?  Does glxinfo indicate that DRI is being used?

**Comment by kirilledelman** [comment]
I'm not running / not installed X11 - I can't test glxgears. My application is entirely command line.

I don't fully understand the how SDL2 or SDL_gpu library pick what rasterization driver to use - is this done at the linking step? At binary start? Does it just look for something that looks like GLESv2 in user library paths, and dynamically links to it at start?

Also, it's probably a question for RPi forums - but Raspberry Pi's current state of native OpenGL support is very confusing. There's some sort of built in driver, then there are two "full kms" and "fake kms" "desktop" drivers that can be enabled from raspi-config tool, but both break boot process with errors for me, and can make system inaccessible. But these are only for X11, right?

I'm still unclear on whether the output is hardware accelerated, is determined by which GLESv2 library you're linking to, or by some other factor.

**Comment by grimfang4** [comment]
If using the SDL_gpu shared library and OpenGL, it will pull in the GL .so dynamically (at program launch-time) under a typical Linux installation.  Not exactly certain about GLES / EGL on the Raspberry Pi.  You can run `ldd` on your binary to see what it will try to link to.

I don't know much about the Raspberry Pi graphics drivers except that they're definitely another project of their own with all that entails.  If the forums do help, fill me in.  It'd be good to know what is going on. :)

**Comment by kirilledelman** [comment]
I got a response with some info about Pi's graphics. It looks like it is actually using the hardware accelerated OpenGL driver. Posting response in case someone else comes here with the same questions: [https://www.raspberrypi.org/forums/viewtopic.php?f=38&t=192017&p=1204684#p1204684](Please explain RPi video driver / OpenGL relationship)

**Comment by kirilledelman** [comment]
One more thing - I found out what my issue was. My SDL build on Raspberry Pi was crap. I think it was because I followed some guide on building SDL that was **supposed to** enable hardware acceleration on RPi, but instead hobbled it somehow. So I was really getting software implementation performance. When I reverted to the SDL build that came with RetroPi distribution, it was flying fast.

**Comment by grimfang4** [comment]
Sweet!
