### ISSUE TITLE
Compiling on Raspberry Pi with Broadcom/VC4 OpenGL lib

### ISSUE THREAD

**Issue by kirilledelman** [grimfang4/sdl-gpu#87]
Hi again.

On my quest for Raspberry Pi Open GL performance, I found [this guide](http://choccyhobnob.com/raspberry-pi/sdl2-2-0-6-on-raspberry-pi/). One important point that I missed before is that on Raspberry Pi, SDL has to be compiled to use Broadcom/VC4 specific OpenGL libraries. In this guide, it had me replace in `SDL/src/video/SDL_egl.c`
```
#if SDL_VIDEO_DRIVER_RPI
/* Raspbian places the OpenGL ES/EGL binaries in a non standard path */
#define DEFAULT_EGL "/opt/vc/lib/libEGL.so"
#define DEFAULT_OGL_ES2 "/opt/vc/lib/libGLESv2.so"
#define DEFAULT_OGL_ES_PVR "/opt/vc/lib/libGLES_CM.so"
#define DEFAULT_OGL_ES "/opt/vc/lib/libGLESv1_CM.so"
```
with 
```
#if SDL_VIDEO_DRIVER_RPI
/* Raspbian places the OpenGL ES/EGL binaries in a non standard path */
#define DEFAULT_EGL "/opt/vc/lib/libbrcmEGL.so"
#define DEFAULT_OGL_ES2 "/opt/vc/lib/libbrcmGLESv2.so"
#define DEFAULT_OGL_ES_PVR "/opt/vc/lib/libbrcmGLESv2.so"
#define DEFAULT_OGL_ES "/opt/vc/lib/libbrcmGLESv2.so"
```

I followed the guide, and recompiled / re-installed SDL2.

Went back to In `sdl-gpu` I've run `cmake -G cmake -G "Unix Makefiles"`, then `make`, and `sudo make install`.

I also changed my own project makefile's to link to Broadcom's versions by replacing `-lEGL` and `-lGLESv2` with `-lbrcmEGL` and `-lbrcmGLESv2`.

Now, I go and compile my project, run it with no performance improvement.

It appears, that it may still be using stock, non-accelerated libraries:
```
$ ldd ./m
	linux-vdso.so.1 (0x7efa3000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76f83000)
	libSDL2-2.0.so.0 => /usr/local/lib/libSDL2-2.0.so.0 (0x76e92000)
	libSDL2_image-2.0.so.0 => /usr/local/lib/libSDL2_image-2.0.so.0 (0x76e62000)
	libSDL2_ttf-2.0.so.0 => /usr/local/lib/libSDL2_ttf-2.0.so.0 (0x76e4c000)
	libSDL2_mixer-2.0.so.0 => /usr/local/lib/libSDL2_mixer-2.0.so.0 (0x76df2000)
	libSDL2_gpu.so => /usr/local/lib/libSDL2_gpu.so (0x76d95000)
*	libbrcmEGL.so => /opt/vc/lib/libbrcmEGL.so (0x76d4a000)
*	libbrcmGLESv2.so => /opt/vc/lib/libbrcmGLESv2.so (0x76d25000)
	libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x76c49000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76bce000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76ba1000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76a5f000)
	libbcm_host.so => /opt/vc/lib/libbcm_host.so (0x76a38000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76a25000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x769fd000)
	librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0x769e6000)
	libfreetype.so.6 => /usr/lib/arm-linux-gnueabihf/libfreetype.so.6 (0x7694d000)
*	libGLESv2.so => /opt/vc/lib/libGLESv2.so (0x76928000)
	libvchiq_arm.so => /opt/vc/lib/libvchiq_arm.so (0x76912000)
	libvcos.so => /opt/vc/lib/libvcos.so (0x768f8000)
	/lib/ld-linux-armhf.so.3 (0x54aaa000)
	libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0x768d0000)
	libpng12.so.0 => /lib/arm-linux-gnueabihf/libpng12.so.0 (0x768a0000)
*	libEGL.so => /opt/vc/lib/libEGL.so (0x76867000)
```

My guess is that SDL_gpu is still linked to the old ones.

How can I force SDL_gpu to use `brcmEGL` and `brcmGLESv2` ?

Thank you.

**Comment by grimfang4** [comment]
Hmm...  Not sure if there's an easy override for it.  You might be able to comment out/delete the OpenGL ES detection in CMakeLists.txt and throw in some `set(SDL_gpu_GL_LIBRARIES ${SDL_gpu_GL_LIBRARIES} brcmEGL brcmGLESv2)`.

**Comment by kuhaut** [comment]
what if you backup the original libs and rename the brcm libraries?

**Comment by kirilledelman** [comment]
I was finally able to link to brcm* libraries by statically linking to SDL_gpu library.

`ldd` reported correct links (no mention of vanilla libEGL, or libGLESv2.

Unfortunately I didn't see a major performance improvement using those libraries.

Thanks for your help anyway!

**Comment by kuhaut** [comment]
Last year i did some gles test on the rpi3 and rpi2 on console (not X) with a onboard compiled version of sdl2 (the hint to get acceleration was to compile sdl2 with -DISABLE_OPENGL flag, like it was linked in your tutorial, without that flag it just crawls)

The test was to bruteforce pixeldraw some sprites off of some texture atlas, and setting the screen fbo pixel by pixel.
rpi3 was about 50% faster than rpi2, and with a 320*240 fbo i got around 80 fps with 1024 tiny sprites. Pixels drawn per frame was somewhere around half a million.
The rpi3 is actually pretty fast (and gets really hot, needs a fan), but the current support for it is all but standardised and a bit of a hassle - mostly because of the bradcom video blob. My experience was that it is much easier to get full acceleration without any x context, so console, sdl2 and fullscreen rendering only.

**Comment by grimfang4** [comment]
If it's possible that the wrong driver is getting used, you can perhaps compare performance between glxgears and a version running via SDL_gpu to get some verification.

I dug up this from a couple of years ago.  It's a modification of an SDL2 port of glxgears, but hopefully its similar enough for comparison:

[sdl_gpu_gears.c.txt](https://github.com/grimfang4/sdl-gpu/files/1286079/sdl_gpu_gears.c.txt)

**Comment by kirilledelman** [comment]
Thank you.

After digging around, it appears that brcmEGL / GLES .lib are really just copies of the other libs. I'm not sure why it's like this.
