### ISSUE TITLE
Antialiasing Shapes

### ISSUE THREAD

**Issue by MrBobBarker** [grimfang4/sdl-gpu#91]
What is a good method to antialias shapes from sdl-gpu such as an Arc? Should this be a built in feature of sdl-gpu?

**Comment by ephemer** [comment]
I was also wondering whether it'd be possible to render circles anti-aliased, which would presumably mean similar changes

**Comment by grimfang4** [comment]
Someone asked about this in an email a few months ago, so here's my edited response:

There's no built-in way to do anti-aliasing with SDL_gpu, so it's currently left to the user.  The obvious/naive way is OpenGL's glEnable( GL_POLYGON_SMOOTH ), but some drivers do not even respond to that.  It's possible that it might work with SDL_gpu on systems that support it.

Supersampling is simple, but wasteful: Render to a 2x larger texture, then blit with linear interpolation (GPU_FILTER_LINEAR) or your own downsampling shader.  A better way might be to look up something like FXAA, which I think is just a shader.

Another way would be to interface with a separate library to do anti-aliased vector drawing.  One such library is NanoVG.  The user I talked to had taken this path and it worked really well for what he was doing.  NanoVG specifically lets you set up the window and GL context independently, so SDL_gpu can do that and NanoVG can take over from there.  You would probably treat NanoVG calls as direct GL calls if you want to also use SDL_gpu's rendering (see 3d-demo for some reference).

If you have any other suggestions or reasonable ways to work AA into SDL_gpu, please share!

**Comment by ephemer** [comment]
Thanks for the tip about NanoVG. I'd tried it out before deciding upon SDL_gpu but it makes sense to combine them. Cheers

**Comment by RandomErrorMessage** [comment]
I'm trying to render NanoVG drawings to a SDL_gpu target and I'm not really sure how I should be doing it. I found if I draw GPU_Rectangle it seems to switch the OpenGL context for NanoVG but then all of my drawing operations are inverted on the y-axis (NanoVG works normally when drawing during the normal render loop).

I've attached an example image with a red and blue box highlighting the specific output. Sorry for putting this here, I'm not sure if I should have opened a new issue but there's already NanoVG discussion here.

![nanovg-invertedy](https://user-images.githubusercontent.com/35673979/35785628-995ede32-09d6-11e8-8c41-6b5f18023874.png)

**Comment by egordorichev** [comment]
Any luck with antialiasing yet? :(

**Comment by grimfang4** [comment]
As per the discussion above, it's probably not going to be a feature of SDL_gpu unless I come across some good AA algorithms and the time to put them in.  I'll close this for now.

**Comment by jarroddavis68** [comment]
Here is what I did for this issue:

```Pascal
// toggle on/off
procedure AntiAliasing(aEnable: Boolean);
begin
  if aEnable then
    begin
      GPU_FlushBlitBuffer;
      glEnable(GL_POLYGON_SMOOTH);
      glHint(GL_POINT_SMOOTH_HINT, GL_NICEST);
    end
  else
    begin
      GPU_FlushBlitBuffer;
      glDisable(GL_POLYGON_SMOOTH);
      GPU_FlushBlitBuffer;
    end;
end;

// toggle on/off and set global flag
procedure GK_AntiAliasing(aEnable: TGK_Bool);
begin
  GKL.AntiAliasing := aEnable;
  AntiAliasing(aEnable);
end;

// if anti-aliasing is enabled, turn if off before rendering a sold primitive, then
// turn it back on and draw an anti-aliased outline around it to smooth the edges
procedure GK_RectangleFilled(aX, aY, aWidth, aHeight: TGK_Single; aColor: TGK_Color);
var
  LColor: SDL_Color absolute aColor;
  LRect: GPU_Rect;
begin
  if not Assigned(GKL.Window.Target) then Exit;
  LRect.x := aX; LRect.y := aY; LRect.w := aWidth; LRect.h := aHeight;
  if GKL.AntiAliasing then AntiAliasing(False);
  GPU_RectangleFilled2(GKL.Window.Target, LRect, LColor);
  if GKL.AntiAliasing then
  begin
    AntiAliasing(True);
    GK_Rectangle(aX, aY, aWidth, aHeight, aColor);
  end;

end;

// for polys such as a images, temp disable if currently enabled then turn it back on afterwards
procedure GK_RenderTexture(aTexture: TGK_Texture; aSrcRect: PGK_Rectangle; aX, aY: TGK_Single; aColor: TGK_Color);
var
  LSrcRect: PGPU_Rect absolute aSrcRect;
  LColor: SDL_Color absolute aColor;
begin
  if not Assigned(aTexture) then Exit;
  GPU_SetColor(aTexture, LColor);
  if GKL.AntiAliasing then AntiAliasing(False);
  GPU_Blit(aTexture, LSrcRect, GKL.Window.Target, aX, aY);
  if GKL.AntiAliasing then AntiAliasing(True);
  GPU_UnsetColor(aTexture);
end;

```

So far so good. 😎
