### ISSUE TITLE
Why not zoom_x and zoom_y for each camera ?

### ISSUE THREAD

**Issue by dhiahassen** [grimfang4/sdl-gpu#92]
Why you didnt use zoom_x and zoom_y for each camera that will allow us to flip a walking animation for example and not to load it twice  by making zoom_x nagative before bliting and then restore it ..... , if you have another solution for that ,like  a simulation for zoom_x/zoom_y , let me know plz , thanks 
Edit  : 
 
- i used ( and developed for ) allegro  library for years and they have this option
- i added it on my local version of sdl_gpu

**Comment by grimfang4** [comment]
This would be a good thing to have.  If your version is all set, you can go ahead and make a pull request.

**Comment by dhiahassen** [comment]
@grimfang4 i have downloaded the last version from the git , i have added this feature , but then you have added something in the sourse so i don't want to update and loose your changes , i know it is not how it works , but by the way , adding this feature now is sooo easy ,  because now sdl gpu uses matrix manipulation everywhere  , i did it in 1 minut

**Comment by 2kreate** [comment]
*Bump* This feature would add to the awesomeness.

Any working examples of using the Camera? I'm still in school so I'm struggling to use the camera. If there was a working example I could look at it would be incredibly helpful.

**Comment by dhiahassen** [comment]
> examples

Not really , i have been using this for my game engine , so it was a feature impleimentation
