### ISSUE TITLE
GPU_MatrixRotate at (0, 0, 0)

### ISSUE THREAD

**Issue by Zulu-Inuoe** [grimfang4/sdl-gpu#93]
I noticed that GPU_MatrixRotate will cause a division by zero when provided with x, y, and z of 0.
Perhaps I'm misunderstanding the purpose of this function, but shouldn't I be able to utilize any x, y, z as a rotation axis?

Thanks.

**Comment by Zulu-Inuoe** [comment]
I apologize profusely. I should have thought about this for more than two seconds. Of course you need an axis of rotation.
My mistake was thinking in 2D only.

**Comment by grimfang4** [comment]
Hey, no problem.  It should work just like glRotatef(), so you need an axis (e.g. (0, 0, 1.0f) for 2D plane rotation) and it needs to be normalized.
