### ISSUE TITLE
Cmake file broken for Visual Studio on Windows (does not create lib or dll files)

### ISSUE THREAD

**Issue by anonanon17** [grimfang4/sdl-gpu#98]
I tried messing around with this for a couple of hours but due to a lack of understanding of CMake I have no idea why this won't generate the .DLL or .LIB files.

I'd just use the pre built binaries, but I can't find any for Windows. It's a shame because this library looks very promising, but it seems very complicated to figure out how to install and setup the thing from scratch.

Do you have any plans to add some kind of tutorial or installation steps? Or even just release a binary for the standard platforms (windows mac linux iOS android)? Either would be super helpful, I'd love to use this library for my projects.

**Comment by DiegoAce** [comment]
I don't believe I had any issues in building the latest commit for Visual Studios. 
I may be forgetting a step because I don't build it often but here's roughly what I did:

```
create 'build' folder inside downloaded sdl_gpu folder.
using cmake gui:
   set source code location to sdl_gpu folder
   set build location to 'build' folder
   configure
   set sdl include path
   set sdl lib path
   configure
   generate
open generated visual studio solution
build for desired configuration (debug release, etc.)
```

**Comment by anonanon17** [comment]
This worked, thanks! I think I must have been missing something obvious without realising it...
