### ISSUE TITLE
Make GPU_MATRIX_STACK_MAX value variable/configurable

### ISSUE THREAD

**Issue by kirilledelman** [grimfang4/sdl-gpu#99]
Jonathan,

I'm using your wonderful library as a backend for a simple game engine, where objects are organized in a hierarchy.

The default value for GPU_MATRIX_STACK_MAX constant is way too low for me (nested object depth can be an arbitrary value). At some point, I'll end up releasing / opening up this library to others, and it feels kind of dumb asking people to modify your source code to set it to a higher value, like 64 or 128.

It would be awesome if this value could be modified at run time, maybe before, or during the SDL-GPU init step, as optional parameter or something.

Thank you.

**Comment by grimfang4** [comment]
Hey, I have already made that change locally for some matrix improvements that I am working on.  I'll double-check everything and push a commit today.

**Comment by grimfang4** [comment]
Actually, it's a little different: the stack grows automatically if you try to push to it when its too small.

**Comment by grimfang4** [comment]
This should work better for you as of 7c190b7c12f2697f5d7e5eae0cc6d418268cfe21.

**Comment by kirilledelman** [comment]
Thanks, Jonathan!
